export const AppOutboxType = {
    GROUP_PRESENCE_SUMMARY: 'GROUP_PRESENCE_SUMMARY',
    RTC_TOPOLOGY_RECOMPUTE: 'RTC_TOPOLOGY_RECOMPUTE',
    GROUP_CONNECT_TRIGGER: 'GROUP_CONNECT_TRIGGER',
    FORMATION_TIMER: 'FORMATION_TIMER',
    TOPOLOGY_PROMOTION: 'TOPOLOGY_PROMOTION',
    ACTIVATION_STATUS_CLOCK: 'ACTIVATION_STATUS_CLOCK'
} as const;

export type AppOutboxType = (typeof AppOutboxType)[keyof typeof AppOutboxType];
