import { useMemo } from 'react';
import { readAuthSessionStorageKind } from '@shared/api/auth.ts';

import type { ArenaConnection } from './arena-connection-contracts.ts';
import { useArenaDiagnosticActions } from './actions/use-arena-diagnostic-actions.ts';
import { useArenaSessionActions } from './actions/use-arena-session-actions.ts';
import { useArenaAiDirectorLifecycle } from './ai/use-arena-ai-director-lifecycle.ts';
import { useArenaCombatActions } from './game-actions/use-arena-combat-actions.ts';
import { useArenaWorldActions } from './game-actions/use-arena-world-actions.ts';
import { useArenaDirectorAppointment } from './match/use-arena-director-appointment.ts';
import { useArenaMatchRuntime } from './match/use-arena-match-runtime.ts';
import { useArenaDirectorMessageHandler } from './messages/use-arena-director-message-handler.ts';
import { useArenaPeerMessageHandlers } from './messages/use-arena-peer-message-handlers.ts';
import { useArenaAvatarProfile } from './state/use-arena-avatar-profile.ts';
import { useArenaPresenceActions } from './state/use-arena-presence-actions.ts';
import { useArenaPresenceLifecycle } from './state/use-arena-presence-lifecycle.ts';
import { useArenaRuntimeState } from './state/use-arena-runtime-state.ts';
import { useArenaStateAcceptance } from './state/use-arena-state-acceptance.ts';
import {
    useArenaConnectionSessionLifecycle,
} from './transport/use-arena-connection-session-lifecycle.ts';
import {
    useArenaNetworkTransportSupport,
} from './transport/use-arena-network-transport-support.ts';
import { useArenaRtcLifecycle } from './transport/use-arena-rtc-lifecycle.ts';

export type {
    ArenaConnection,
    ArenaDiagnosticsRefreshOptions,
    ArenaHttpDiagnostics,
    ArenaTransportDiagnostics,
    DirectorAttemptState,
    HttpProbeDiagnostics,
} from './arena-connection-contracts.ts';

export function useRallarArena(): ArenaConnection {
    const state = useArenaRuntimeState();
    const {
        activeEvent,
        activeMatchRoomIdRef,
        aiError,
        aiStatus,
        arenaMatchRef,
        arenaSnapshot,
        arenaSnapshotRef,
        bumpNetworkGeneration,
        clearPendingReliableArenaSnapshot,
        clearRoomScopedArenaState,
        connectionState,
        currentNetworkSignal,
        diagnosticsRefreshRef,
        directorAttempt,
        directorAttemptRef,
        directorStatus,
        directorStatusRef,
        error,
        gameDiagnostics,
        httpDiagnostics,
        isCurrentNetworkGeneration,
        isNetworkEnabled,
        localAvatarProfileRef,
        networkGenerationRef,
        pickupAcceptances,
        poseSendBudget,
        presenceDirectorLabelRef,
        presenceInitializedRef,
        presenceLinkRef,
        presenceNotices,
        presencePlayersRef,
        reliableSnapshotLastSentAtRef,
        reliableSnapshotLastSentRevisionRef,
        reliableSnapshotPendingRef,
        reliableSnapshotTimerRef,
        remoteEvents,
        remotePlayerHits,
        remotePlayers,
        remoteShots,
        resetForSignedOutAuth,
        roomId,
        roomIdRef,
        rooms,
        rtcLanes,
        session,
        sessionRef,
        setActiveEvent,
        setAiError,
        setAiStatus,
        setArenaSnapshot,
        setConnectionState,
        setDirectorAttempt,
        setDirectorStatus,
        setError,
        setGameDiagnostics,
        setHttpDiagnostics,
        setPickupAcceptances,
        setPresenceNotices,
        setRemoteEvents,
        setRemotePlayerHits,
        setRemotePlayers,
        setRemoteShots,
        setRoomId,
        setRooms,
        setRtcLanes,
        setSession,
        setTransportDiagnostics,
        snapshotLaneReadySyncKeyRef,
        transportDiagnostics,
        transportDiagnosticsRef,
    } = state;

    const { dismissPresenceNotice, linkState } = useArenaPresenceLifecycle({
        connectionState,
        directorStatus,
        isNetworkEnabled,
        presenceDirectorLabelRef,
        presenceInitializedRef,
        presenceLinkRef,
        presenceNotices,
        presencePlayersRef,
        remotePlayers,
        roomId,
        rtcLanes,
        session,
        setPresenceNotices,
        transportDiagnostics,
    });
    useArenaAvatarProfile({
        arenaSnapshotRef,
        isCurrentNetworkGeneration,
        localAvatarProfileRef,
        networkGenerationRef,
        roomId,
        session,
    });

    const { runBestEffortNetworkTask, scheduleReliableArenaSnapshot } =
        useArenaNetworkTransportSupport({
            arenaMatchRef,
            arenaSnapshotRef,
            clearPendingReliableArenaSnapshot,
            directorStatusRef,
            isCurrentNetworkGeneration,
            localAvatarProfileRef,
            networkGenerationRef,
            reliableSnapshotLastSentAtRef,
            reliableSnapshotLastSentRevisionRef,
            reliableSnapshotPendingRef,
            reliableSnapshotTimerRef,
            roomId,
            roomIdRef,
            session,
            setTransportDiagnostics,
        });
    const { acceptPlayerHit, acceptPickup, acceptEyeAttack, acceptMatchStartIntent } =
        useArenaStateAcceptance({
            arenaMatchRef,
            arenaSnapshotRef,
            roomIdRef,
            setActiveEvent,
            setArenaSnapshot,
            setPickupAcceptances,
            setRemoteEvents,
            setRemotePlayerHits,
        });
    const acceptDirectorOutput = useArenaDirectorMessageHandler({
        acceptEyeAttack,
        acceptPickup,
        acceptPlayerHit,
        arenaSnapshotRef,
        roomIdRef,
        sessionRef,
        setActiveEvent,
        setArenaSnapshot,
        setRemoteEvents,
        setRemotePlayers,
        setRemoteShots,
    });
    const { acceptMotionMessage, acceptRealtimeMessage } = useArenaPeerMessageHandlers({
        acceptEyeAttack,
        acceptPickup,
        acceptPlayerHit,
        sessionRef,
        setActiveEvent,
        setArenaSnapshot,
        setRemoteEvents,
        setRemotePlayers,
        setRemoteShots,
    });

    const { connect } = useArenaConnectionSessionLifecycle({
        acceptMotionMessage,
        acceptRealtimeMessage,
        bumpNetworkGeneration,
        connectionState,
        currentNetworkSignal,
        isCurrentNetworkGeneration,
        roomIdRef,
        setConnectionState,
        setDirectorStatus,
        setError,
        setRemotePlayers,
        setRoomId,
        setRooms,
        setSession,
    });
    useArenaRtcLifecycle({
        arenaMatchRef,
        connectionState,
        isCurrentNetworkGeneration,
        isNetworkEnabled,
        networkGenerationRef,
        roomId,
        rtcLanes,
        runBestEffortNetworkTask,
        setGameDiagnostics,
        setRtcLanes,
        snapshotLaneReadySyncKeyRef,
    });
    const { attemptDirectorAppointment } = useArenaDirectorAppointment({
        arenaMatchRef,
        isCurrentNetworkGeneration,
        networkGenerationRef,
        roomIdRef,
        setDirectorAttempt,
        setDirectorStatus,
        setGameDiagnostics,
    });
    useArenaMatchRuntime({
        acceptDirectorOutput,
        acceptMatchStartIntent,
        acceptMotionMessage,
        acceptPickup,
        acceptPlayerHit,
        activeMatchRoomIdRef,
        arenaMatchRef,
        arenaSnapshotRef,
        bumpNetworkGeneration,
        connectionState,
        isCurrentNetworkGeneration,
        networkGenerationRef,
        roomId,
        roomIdRef,
        runBestEffortNetworkTask,
        setActiveEvent,
        setArenaSnapshot,
        setDirectorStatus,
        setError,
        setGameDiagnostics,
        setRemoteEvents,
    }, attemptDirectorAppointment);
    useArenaAiDirectorLifecycle({
        arenaMatchRef,
        arenaSnapshotRef,
        connectionState,
        directorStatus,
        isCurrentNetworkGeneration,
        networkGenerationRef,
        roomId,
        runBestEffortNetworkTask,
        setActiveEvent,
        setAiError,
        setAiStatus,
        setRemoteEvents,
    });

    const sessionActions = useArenaSessionActions({
        attemptDirectorAppointment,
        clearRoomScopedArenaState,
        connect,
        connectionState,
        directorAttemptRef,
        directorStatusRef,
        isNetworkEnabled,
        resetForSignedOutAuth,
        roomId,
        roomIdRef,
        rooms,
        sessionRef,
        setConnectionState,
        setError,
        setRoomId,
        setRooms,
        setSession,
    });
    const diagnosticActions = useArenaDiagnosticActions({
        arenaMatchRef,
        currentNetworkSignal,
        diagnosticsRefreshRef,
        isCurrentNetworkGeneration,
        isNetworkEnabled,
        networkGenerationRef,
        sessionRef,
        setGameDiagnostics,
        setHttpDiagnostics,
        setPresenceNotices,
        setRtcLanes,
        setTransportDiagnostics,
        transportDiagnosticsRef,
    });
    const presenceActions = useArenaPresenceActions({
        arenaMatchRef,
        isNetworkEnabled,
        localAvatarProfileRef,
        networkGenerationRef,
        poseSendBudget,
        roomIdRef,
        runBestEffortNetworkTask,
        sessionRef,
    });
    const combatActions = useArenaCombatActions({
        acceptPlayerHit,
        arenaMatchRef,
        arenaSnapshotRef,
        directorStatusRef,
        isNetworkEnabled,
        networkGenerationRef,
        roomIdRef,
        runBestEffortNetworkTask,
        sessionRef,
        setArenaSnapshot,
    });
    const worldActions = useArenaWorldActions({
        acceptMatchStartIntent,
        acceptPickup,
        arenaMatchRef,
        arenaSnapshotRef,
        directorStatusRef,
        isNetworkEnabled,
        networkGenerationRef,
        roomIdRef,
        runBestEffortNetworkTask,
        scheduleReliableArenaSnapshot,
        sessionRef,
        setArenaSnapshot,
    });

    return useMemo(() => ({
        session,
        connectionState,
        error,
        roomId,
        rooms,
        directorStatus,
        rtcLanes,
        directorAttempt,
        gameDiagnostics,
        transportDiagnostics,
        httpDiagnostics,
        linkState,
        presenceNotices,
        authStorageKind: readAuthSessionStorageKind(),
        authGeneration: networkGenerationRef.current,
        networkEnabled: isNetworkEnabled(),
        logoutQuiesced: connectionState === 'signed-out' &&
            !sessionRef.current &&
            !roomIdRef.current &&
            !arenaMatchRef.current,
        aiStatus,
        aiError,
        activeEvent,
        arenaSnapshot,
        remoteEvents,
        remotePlayers,
        remoteShots,
        remotePlayerHits,
        pickupAcceptances,
        ...sessionActions,
        ...diagnosticActions,
        dismissPresenceNotice,
        ...presenceActions,
        ...combatActions,
        ...worldActions,
    }), [
        activeEvent,
        aiError,
        aiStatus,
        arenaMatchRef,
        arenaSnapshot,
        combatActions,
        connectionState,
        diagnosticActions,
        directorAttempt,
        directorStatus,
        dismissPresenceNotice,
        error,
        gameDiagnostics,
        httpDiagnostics,
        isNetworkEnabled,
        linkState,
        networkGenerationRef,
        pickupAcceptances,
        presenceActions,
        presenceNotices,
        remoteEvents,
        remotePlayerHits,
        remotePlayers,
        remoteShots,
        roomId,
        roomIdRef,
        rooms,
        rtcLanes,
        session,
        sessionActions,
        sessionRef,
        transportDiagnostics,
        worldActions,
    ]);
}
