import type {QueueBoxResourceEntryRepository,} from "../queuebox/QueueBoxTypes.ts";
import {JsonWebSocketServer} from "./JsonWebSocketServer.ts";
import {Key, toResourceEntry} from "../queuebox/ResourceEntry.ts";
import {DequeueResourceEntryController, ResilienceDto} from "../queuebox/DequeueResourceEntryController.ts";
import {DequeueController} from "../queuebox/DequeueController.ts";
import {OnInboxWebSocketMessageCallback} from "./inbox-outbox-contracts.ts";

export type WsQueueBoxServerServiceInputDto = {
    typeId: string
}

export type WsQueueBoxInboxDto = {
    id: string,
    data: unknown
}

export class WsQueueBoxServerService {
    private readonly typesToDequeue: Set<string>;

    private readonly onInboxWebSocketMessageCallbacks: Map<string, OnInboxWebSocketMessageCallback<WsQueueBoxInboxDto>> = new Map<string, OnInboxWebSocketMessageCallback<WsQueueBoxInboxDto>>();

    /**
     * @param inbox - QueueBoxResourceEntryRepository for incoming messages from clients
     * @param outbox - QueueBoxResourceEntryRepository for outgoing messages generated by the server
     * @param socket - JsonWebSocketServer for handling WebSocket connections
     * @param input - Input configuration for the service
     */
    constructor(
        public readonly inbox: QueueBoxResourceEntryRepository,
        public readonly outbox: QueueBoxResourceEntryRepository,
        public readonly socket: JsonWebSocketServer,
        public readonly input: WsQueueBoxServerServiceInputDto
    ) {
        this.typesToDequeue = new Set([this.input.typeId]);

        // Write incoming messages to this.inbox
        this.socket.onMessageDo(
            this.input.typeId,
            {
                onMessage: (ctx, data) => {
                    this.inbox.enqueue(
                        toResourceEntry<WsQueueBoxInboxDto>(
                            this.input.typeId,
                            {
                                id: ctx.id,
                                data: data
                            },
                        )
                    )
                }
            }
        )
    }

    onInboxMessageDo(id: string, callback: OnInboxWebSocketMessageCallback<WsQueueBoxInboxDto>): WsQueueBoxServerService {
        this.onInboxWebSocketMessageCallbacks.set(id, callback);
        return this;
    }

    removeInboxMessageCallback(id: string): boolean {
        return this.onInboxWebSocketMessageCallbacks.delete(id);
    }

    // dequeue and call handlers that can forward to a list of connections
    async dequeueInboxToSend(resilience: ResilienceDto) {
        if (resilience.isNotAllowedThroughToDequeue()) {
            console.warn("Dequeue blocked {}, circuit state {}", this.typesToDequeue, resilience.circuitBreaker.state.get());
            return;
        }

        await DequeueResourceEntryController.toDequeuer<Key>(
                this.inbox,
                () => this.typesToDequeue,
                () => DequeueController.DEFAULT_MAX_NUM_TO_RESERVE,
                DequeueController.DEFAULT_MAX_RETRY,
                DequeueController.DEFAULT_MAX_NUM_TO_DEQUEUE,
                resilience
            )
            .onFailedEntries(
                _ => resilience.failure()
            )
            .onCompletedEntries(
                _ => resilience.success()
            )
            .dequeueForCompute(
                (key, entry) => {
                    for (const callback of this.onInboxWebSocketMessageCallbacks.values()) {
                        try {
                            callback.onMessage(
                                JSON.parse(entry.resource),
                                entry,
                                this.socket
                            )
                        } catch (e) {
                            console.error("Error calling onMessage callback", e)
                        }
                    }
                    return key
                }
            )
    }
}
