export enum AppOutboxType {
    GROUP_PRESENCE_SUMMARY = 'GROUP_PRESENCE_SUMMARY',
    RTC_TOPOLOGY_RECOMPUTE = 'RTC_TOPOLOGY_RECOMPUTE',
    STATE_MUTATION_OUTBOX_DRAIN = 'STATE_MUTATION_OUTBOX_DRAIN',
}
