import type { RallarFacade } from '@shared-web/browser/rallar-facade-contract.ts';
import { createBrowserRallarFacade } from '@shared-web/browser/rallar-runtime/compose.ts';

export {
    createRallarDataFacade,
    defineRallarDataStore,
} from '@shared-web/browser/rallar-data.ts';

export {
    createRallarCrdtFacade,
} from '@shared-web/browser/rallar-crdt.ts';

export {
    matchesRallarMessageSelector,
    normalizeRallarMessageSelector,
} from '@shared-web/browser/rallar-message-selectors.ts';

export {
    evaluateRallarReadinessExpectation,
    normalizeRallarReadinessExpectation,
} from '@shared-web/browser/readiness.ts';

export type {
    RallarCrdtDocument,
    RallarCrdtFacade,
    RallarCrdtFacadeDefaults,
    RallarCrdtOpenOptions,
    RallarCrdtOpenScope,
    RallarCrdtSnapshotListener,
} from '@shared-web/browser/rallar-crdt.ts';

export type {
    RallarDataChangeEvent,
    RallarDataChangeListener,
    RallarDataDurability,
    RallarDataFacade,
    RallarDataHydration,
    RallarDataMigration,
    RallarDataMigrationContext,
    RallarDataScope,
    RallarDataStorageEstimate,
    RallarDataStore,
    RallarDataStoreDefinition,
    RallarDataStoreOptions,
} from '@shared-web/browser/rallar-data.ts';

export type {
    RallarMessageSelector,
    RallarMessageSelectorInput,
} from '@shared-web/browser/rallar-message-selectors.ts';

export type {
    RallarStatsFacade,
    RallarStatsGroupInput,
    RallarStatsReadOptions,
} from '@shared-web/browser/rallar-stats-facade.ts';

export type {
    RallarOperationOptions,
    RallarOperationRetryPredicate,
} from '@shared-web/browser/rallar-operation-options.ts';

export type {
    RallarNormalizedReadinessExpectation,
    RallarReadinessEvaluation,
    RallarReadinessExpectation,
    RallarReadinessStatus,
} from '@shared-web/browser/readiness.ts';

export type {
    RallarUnsubscribe,
    RallarStateListener,
    RallarAuthChangeReason,
    RallarAuthState,
    RallarAuthChangeListener,
    RallarConnectStatus,
    RallarFlow,
    RallarFlowPolicies,
    RallarDefaults,
    RallarRegisterOptions,
    RallarScopedOperationOptions,
    RallarRefreshOptions,
    RallarStartOptions,
    RallarStartResult,
    RallarSetupInput,
    RallarSubscriptionScope,
    RallarRoomSummary,
    RallarRoomMember,
    RallarRoomState,
    RallarRoomPresenceWaitOptions,
    RallarRoomPresenceWaitResult,
    RallarPerson,
    RallarPeopleState,
    RallarCreateRoomInput,
    RallarRoomTargetInput,
    RallarUpdateRoomInput,
    RallarRoomLifecycleOptions,
    RallarRoomInviteOptions,
    RallarRoomGovernanceOptions,
    RallarJoinRoomOptions,
    RallarJoinRoomInput,
    RallarRoomSwitchOperation,
    RallarRoomSwitchPartialFailureError,
    RallarLeaveRoomOptions,
    RallarOnChangeOptions,
    RallarRoomEventOptions,
    RallarPeopleEventOptions,
    RallarListRoomEventsOptions,
    RallarListRoomEventsInput,
    RallarReplayEventsResult,
    RallarReplayRoomEventsOptions,
    RallarReplayRoomEventsInput,
    RallarListPeopleEventsOptions,
    RallarReplayPeopleEventsOptions,
    RallarWaitForOpenStatus,
    RallarWaitForOpenOptions,
    RallarRtcWaitForOpenOptions,
    RallarRtcRoomLaneWaitOptions,
    RallarRtcRoomLaneWaitStatus,
    RallarRtcRoomMode,
    RallarRoomTransportState,
    RallarRoomTransportStatus,
    RallarRtcRoomTransportOptions,
    RallarTypedMessageSendStrategy,
    RallarMessageTransport,
    RallarMessage,
    RallarMessageHandler,
    RallarStateEventListener,
    RallarRoomEventListener,
    RallarPeopleEventListener,
    RallarMessageSendBase,
    RallarRtcSendInput,
    RallarWsSendInput,
    RallarMessageSendStatus,
    RallarMessageSendResult,
    RallarMessageLane,
    RallarTypedMessageChannelDefinition,
    RallarTypedPayloadHandler,
    RallarTypedRtcSendOptions,
    RallarTypedWsSendOptions,
    RallarTypedMessageSendOptions,
    RallarTypedMessageChannel,
    RallarRoomMessageChannelDefinition,
    RallarRoomMessageChannel,
    RallarRoomSessionRealtimeInput,
    RallarRoomSessionMessageDefinition,
    RallarRoomSession,
    RallarRemoteStream,
    RallarMediaSourceKind,
    RallarMediaSourceState,
    RallarMediaSourceStatus,
    RallarMediaSourceHandle,
    RallarMediaSourceAttachOptions,
    RallarMicrophoneSourceStartOptions,
    RallarCameraSourceStartOptions,
    RallarScreenSourceStartOptions,
    RallarMediaSourceController,
    RallarMediaSourcesFacade,
    RallarRealtimeSendOptions,
    RallarRealtimeJsonSendInput,
    RallarRealtimeBinarySendInput,
    RallarRealtimeSendResult,
    RallarRealtimeJsonLaneDefaults,
    RallarRealtimeJsonLaneSendOptions,
    RallarRealtimeJsonLane,
    RallarRoomRealtimeSendStatus,
    RallarRoomRealtimeJsonDefaults,
    RallarRoomRealtimeJsonSendOptions,
    RallarRoomRealtimeTransportOptions,
    RallarRoomRealtimeSendResult,
    RallarRoomRealtimeJsonChannel,
    RallarTargetMembership,
    RallarTargetSelector,
    RallarTargetedChannelDefinition,
    RallarTargetedChannelSendOptions,
    RallarTargetedSendStatus,
    RallarTargetedSendResult,
    RallarTargetedChannel,
    RallarRealtimeMessage,
    RallarRealtimeHandler,
    RallarRealtimeHealthOptions,
    RallarRealtimeLaneHealth,
    RallarRtcStatusOptions,
    RallarRtcStatusSubscriptionOptions,
    RallarRtcStatusListener,
    RallarRtcLifecycleKind,
    RallarRtcLifecycleEvent,
    RallarRtcLifecycleListener,
    RallarRtcPeerConnectionStatus,
    RallarRtcLaneStatus,
    RallarRtcPeerStatus,
    RallarRtcStatus,
    RallarRtcDiagnosticsOptions,
    RallarRtcCandidateDiagnostics,
    RallarRtcCandidatePairDiagnostics,
    RallarRtcPeerDiagnostics,
    RallarRtcDiagnostics,
    RallarRtcRecoveryStatus,
    RallarRtcRecoveryResult,
    RallarRtcReconnectOptions,
    RallarWsReadyState,
    RallarWsStatus,
    RallarWsWaitForOpenResult,
    RallarWsStatusSubscriptionOptions,
    RallarWsStatusListener,
    RallarWsLifecycleKind,
    RallarWsLifecycleEvent,
    RallarWsLifecycleListener,
    RallarRtcWaitForOpenResult,
    RallarRtcRoomLaneWaitResult,
    RallarCallMediaInput,
    RallarCallDataInput,
    RallarCallStartInput,
    RallarCallParticipantState,
    RallarCallState,
    RallarCallParticipantStatus,
    RallarCallStatus,
    RallarCallWaitOptions,
    RallarCallEndOptions,
    RallarCallSignalKind,
    RallarCallSignalPayload,
    RallarCallInviteInput,
    RallarCallSignalSend,
    RallarCallInviteResult,
    RallarDirectorRole,
    RallarDirectorState,
    RallarDirectorStatus,
    RallarDirectorAppointOptions,
    RallarDirectorResignOptions,
    RallarDirectorStatusOptions,
    RallarDirectorStatusListener,
    RallarDirectorRelayEnvelope,
    RallarDirectorRelayMessage,
    RallarDirectorRelaySendStatus,
    RallarDirectorRelaySendResult,
    RallarDirectorRelayConfig,
    RallarDirectorRelayHandle,
    RallarCallSignalEvent,
    RallarIncomingCallInvite,
    RallarCallSignalListener,
    RallarCallInviteListener,
    RallarCallHandle,
    RallarFacade,
} from '@shared-web/browser/rallar-facade-contract.ts';

export function createRallarFacade(): RallarFacade {
    return createBrowserRallarFacade();
}

export const rallar: RallarFacade = createRallarFacade();
