import { describe, expect, it } from 'vitest';
import { collectExportSnapshot, type ExportSnapshot } from './public-api-snapshot-collector.ts';

interface PublicSurfaceSnapshot {
    readonly filePath: string;
    readonly resolveStarExports?: boolean;
    readonly expected: ExportSnapshot;
}

const PUBLIC_SURFACES: readonly PublicSurfaceSnapshot[] = [
    {
        filePath: 'packages/shared-web/browser/rallar.ts',
        expected: {
            values: [
                'createRallarCrdtFacade',
                'createRallarDataFacade',
                'createRallarFacade',
                'defineRallarDataStore',
                'evaluateRallarReadinessExpectation',
                'matchesRallarMessageSelector',
                'normalizeRallarMessageSelector',
                'normalizeRallarReadinessExpectation',
                'rallar'
            ],
            types: [
                'CommandsOrchestrator',
                'CommandsOrchestratorPolicies',
                'CreateRallarDataFacadeInput',
                'RallarAdvancedFacade',
                'RallarAuthChangeListener',
                'RallarAuthChangeReason',
                'RallarAuthState',
                'RallarCallDataInput',
                'RallarCallEndOptions',
                'RallarCallHandle',
                'RallarCallInviteInput',
                'RallarCallInviteListener',
                'RallarCallInviteResult',
                'RallarCallMediaInput',
                'RallarCallParticipantState',
                'RallarCallParticipantStatus',
                'RallarCallSignalEvent',
                'RallarCallSignalKind',
                'RallarCallSignalListener',
                'RallarCallSignalPayload',
                'RallarCallSignalSend',
                'RallarCallStartInput',
                'RallarCallState',
                'RallarCallStatus',
                'RallarCameraSourceStartOptions',
                'RallarChannelsFacade',
                'RallarConnectStatus',
                'RallarCrdtDocument',
                'RallarCrdtFacade',
                'RallarCrdtFacadeDefaults',
                'RallarCrdtOpenOptions',
                'RallarCrdtOpenScope',
                'RallarCrdtSnapshotListener',
                'RallarCreateRoomInput',
                'RallarDataChangeEvent',
                'RallarDataChangeListener',
                'RallarDataDurability',
                'RallarDataFacade',
                'RallarDataHydration',
                'RallarDataMigration',
                'RallarDataMigrationContext',
                'RallarDataScope',
                'RallarDataStorageEstimate',
                'RallarDataStore',
                'RallarDataStoreDefinition',
                'RallarDataStoreOptions',
                'RallarDefaults',
                'RallarDirectorAppointOptions',
                'RallarDirectorRelayConfig',
                'RallarDirectorRelayEnvelope',
                'RallarDirectorRelayHandle',
                'RallarDirectorRelayMessage',
                'RallarDirectorRelaySendResult',
                'RallarDirectorRelaySendStatus',
                'RallarDirectorRole',
                'RallarDirectorState',
                'RallarDirectorStatus',
                'RallarDirectorStatusListener',
                'RallarDirectorStatusOptions',
                'RallarFacade',
                'RallarIncomingCallInvite',
                'RallarJoinRoomInput',
                'RallarJoinRoomOptions',
                'RallarLeaveRoomOptions',
                'RallarListPeopleEventsOptions',
                'RallarListRoomEventsInput',
                'RallarListRoomEventsOptions',
                'RallarMediaSourceAttachOptions',
                'RallarMediaSourceController',
                'RallarMediaSourceHandle',
                'RallarMediaSourceKind',
                'RallarMediaSourceState',
                'RallarMediaSourceStatus',
                'RallarMediaSourcesFacade',
                'RallarMessage',
                'RallarMessageHandler',
                'RallarMessageLane',
                'RallarMessageSelector',
                'RallarMessageSelectorInput',
                'RallarMessageSendBase',
                'RallarMessageSendResult',
                'RallarMessageTransport',
                'RallarMicrophoneSourceStartOptions',
                'RallarNormalizedReadinessExpectation',
                'RallarOnChangeOptions',
                'RallarOperationOptions',
                'RallarOperationRetryPredicate',
                'RallarPeopleEventOptions',
                'RallarPeopleState',
                'RallarPerson',
                'RallarProductFacade',
                'RallarReadinessEvaluation',
                'RallarReadinessExpectation',
                'RallarReadinessStatus',
                'RallarRealtimeBinarySendInput',
                'RallarRealtimeHandler',
                'RallarRealtimeHealthOptions',
                'RallarRealtimeJsonLane',
                'RallarRealtimeJsonLaneSendOptions',
                'RallarRealtimeJsonSendInput',
                'RallarRealtimeLaneHealth',
                'RallarRealtimeMessage',
                'RallarRealtimeSendOptions',
                'RallarRealtimeSendResult',
                'RallarRegisterOptions',
                'RallarRemoteStream',
                'RallarReplayEventsResult',
                'RallarReplayPeopleEventsOptions',
                'RallarReplayRoomEventsInput',
                'RallarReplayRoomEventsOptions',
                'RallarRoomEventOptions',
                'RallarRoomGovernanceOptions',
                'RallarRoomInviteOptions',
                'RallarRoomLifecycleOptions',
                'RallarRoomMember',
                'RallarRoomMessageChannelDefinition',
                'RallarRoomPresenceWaitOptions',
                'RallarRoomPresenceWaitResult',
                'RallarRoomRealtimeJsonChannel',
                'RallarRoomRealtimeJsonDefaults',
                'RallarRoomRealtimeJsonSendOptions',
                'RallarRoomRealtimeSendResult',
                'RallarRoomRealtimeSendStatus',
                'RallarRoomRealtimeTransportOptions',
                'RallarRoomSession',
                'RallarRoomSessionMessageDefinition',
                'RallarRoomSessionRealtimeInput',
                'RallarRoomState',
                'RallarRoomSummary',
                'RallarRoomSwitchOperation',
                'RallarRoomSwitchPartialFailureError',
                'RallarRoomTargetInput',
                'RallarRoomTransportState',
                'RallarRoomTransportStatus',
                'RallarRtcCandidateDiagnostics',
                'RallarRtcCandidatePairDiagnostics',
                'RallarRtcDiagnostics',
                'RallarRtcDiagnosticsOptions',
                'RallarRtcLaneStatus',
                'RallarRtcLifecycleEvent',
                'RallarRtcLifecycleKind',
                'RallarRtcLifecycleListener',
                'RallarRtcPeerConnectionStatus',
                'RallarRtcPeerDiagnostics',
                'RallarRtcPeerStatus',
                'RallarRtcReconnectOptions',
                'RallarRtcRecoveryResult',
                'RallarRtcRecoveryStatus',
                'RallarRtcRoomLaneWaitOptions',
                'RallarRtcRoomLaneWaitResult',
                'RallarRtcRoomLaneWaitStatus',
                'RallarRtcRoomMode',
                'RallarRtcRoomTransportOptions',
                'RallarRtcSendInput',
                'RallarRtcStatus',
                'RallarRtcStatusListener',
                'RallarRtcStatusOptions',
                'RallarRtcStatusSubscriptionOptions',
                'RallarRtcWaitForOpenOptions',
                'RallarRtcWaitForOpenResult',
                'RallarScopedOperationOptions',
                'RallarScreenSourceStartOptions',
                'RallarSetRoomMemberRoleInput',
                'RallarSetupInput',
                'RallarStartOptions',
                'RallarStartResult',
                'RallarStateEventListener',
                'RallarStateListener',
                'RallarSubscriptionScope',
                'RallarTargetMembership',
                'RallarTargetSelector',
                'RallarTargetedChannel',
                'RallarTargetedChannelDefinition',
                'RallarTargetedChannelSendOptions',
                'RallarTargetedSendResult',
                'RallarTargetedSendStatus',
                'RallarTypedMessageChannel',
                'RallarTypedMessageChannelDefinition',
                'RallarTypedMessageSendOptions',
                'RallarTypedMessageSendStrategy',
                'RallarTypedPayloadHandler',
                'RallarTypedRtcSendOptions',
                'RallarTypedWsSendOptions',
                'RallarUnsubscribe',
                'RallarUpdateRoomInput',
                'RallarWaitForOpenOptions',
                'RallarWaitForOpenStatus',
                'RallarWsFacade',
                'RallarWsLifecycleEvent',
                'RallarWsLifecycleKind',
                'RallarWsLifecycleListener',
                'RallarWsReadyState',
                'RallarWsSendInput',
                'RallarWsStatus',
                'RallarWsStatusListener',
                'RallarWsWaitForOpenResult'
            ],
            starExports: [],
            namespaceExports: []
        }
    },
    {
        filePath: 'packages/shared-web/browser/rallar-core.ts',
        expected: {
            values: [
                'configureApiClient',
                'matchesRallarMessageSelector',
                'normalizeApiBaseUrl',
                'normalizeRallarMessageSelector',
                'readApiBaseUrl'
            ],
            types: [
                'CommandsOrchestrator',
                'CommandsOrchestratorPolicies',
                'RallarApiClientConfig',
                'RallarAuthChangeListener',
                'RallarAuthChangeReason',
                'RallarAuthFacade',
                'RallarAuthState',
                'RallarConnectStatus',
                'RallarConnectionFacade',
                'RallarConnectionOperations',
                'RallarCreateRoomInput',
                'RallarDefaults',
                'RallarJoinRoomOptions',
                'RallarLeaveRoomOptions',
                'RallarListPeopleEventsOptions',
                'RallarListRoomEventsInput',
                'RallarListRoomEventsOptions',
                'RallarMessage',
                'RallarMessageHandler',
                'RallarMessageLane',
                'RallarMessageSelector',
                'RallarMessageSelectorInput',
                'RallarMessageSendBase',
                'RallarMessageSendResult',
                'RallarMessageTransport',
                'RallarOnChangeOptions',
                'RallarOperationOptions',
                'RallarOperationRetryPredicate',
                'RallarPeopleEventOptions',
                'RallarPeopleState',
                'RallarPerson',
                'RallarRegisterOptions',
                'RallarReplayEventsResult',
                'RallarReplayPeopleEventsOptions',
                'RallarReplayRoomEventsInput',
                'RallarReplayRoomEventsOptions',
                'RallarRoomEventOptions',
                'RallarRoomMember',
                'RallarRoomMessageChannelDefinition',
                'RallarRoomSession',
                'RallarRoomSessionMessageDefinition',
                'RallarRoomSessionRealtimeInput',
                'RallarRoomState',
                'RallarRoomSummary',
                'RallarRoomSwitchOperation',
                'RallarRoomSwitchPartialFailureError',
                'RallarRtcSendInput',
                'RallarScopedOperationOptions',
                'RallarSetupInput',
                'RallarStartOptions',
                'RallarStartResult',
                'RallarStateEventListener',
                'RallarStateListener',
                'RallarSubscriptionScope',
                'RallarTypedMessageChannel',
                'RallarTypedMessageChannelDefinition',
                'RallarTypedMessageSendOptions',
                'RallarTypedMessageSendStrategy',
                'RallarTypedPayloadHandler',
                'RallarTypedRtcSendOptions',
                'RallarTypedWsSendOptions',
                'RallarUnsubscribe',
                'RallarWsSendInput'
            ],
            starExports: [],
            namespaceExports: []
        }
    },
    {
        filePath: 'packages/shared-web/browser/rallar-realtime.ts',
        expected: {
            values: [],
            types: [
                'RallarRealtimeBinarySendInput',
                'RallarRealtimeFacade',
                'RallarRealtimeHandler',
                'RallarRealtimeHealthOptions',
                'RallarRealtimeJsonLane',
                'RallarRealtimeJsonLaneSendOptions',
                'RallarRealtimeJsonSendInput',
                'RallarRealtimeLaneHealth',
                'RallarRealtimeMessage',
                'RallarRealtimeSendOptions',
                'RallarRealtimeSendResult',
                'RallarRoomRealtimeJsonChannel',
                'RallarRoomRealtimeJsonDefaults',
                'RallarRoomRealtimeJsonSendOptions',
                'RallarRoomRealtimeSendResult',
                'RallarRoomRealtimeSendStatus',
                'RallarRoomRealtimeTransportOptions',
                'RallarRoomTransportState',
                'RallarRoomTransportStatus',
                'RallarRtcCandidateDiagnostics',
                'RallarRtcCandidatePairDiagnostics',
                'RallarRtcDiagnostics',
                'RallarRtcDiagnosticsOptions',
                'RallarRtcFacade',
                'RallarRtcLaneStatus',
                'RallarRtcLifecycleEvent',
                'RallarRtcLifecycleKind',
                'RallarRtcLifecycleListener',
                'RallarRtcPeerConnectionStatus',
                'RallarRtcPeerDiagnostics',
                'RallarRtcPeerStatus',
                'RallarRtcReconnectOptions',
                'RallarRtcRecoveryResult',
                'RallarRtcRecoveryStatus',
                'RallarRtcRoomLaneWaitOptions',
                'RallarRtcRoomLaneWaitResult',
                'RallarRtcRoomLaneWaitStatus',
                'RallarRtcRoomMode',
                'RallarRtcRoomTransportOptions',
                'RallarRtcStatus',
                'RallarRtcStatusListener',
                'RallarRtcStatusOptions',
                'RallarRtcStatusSubscriptionOptions',
                'RallarRtcWaitForOpenOptions',
                'RallarRtcWaitForOpenResult',
                'RallarWaitForOpenOptions',
                'RallarWaitForOpenStatus'
            ],
            starExports: ['@shared-web/browser/rallar-core.ts'],
            namespaceExports: []
        }
    },
    {
        filePath: 'packages/shared-web/browser/rallar-media-calls.ts',
        expected: {
            values: [],
            types: [
                'RallarCallDataInput',
                'RallarCallEndOptions',
                'RallarCallHandle',
                'RallarCallInviteInput',
                'RallarCallInviteListener',
                'RallarCallInviteResult',
                'RallarCallMediaInput',
                'RallarCallParticipantState',
                'RallarCallParticipantStatus',
                'RallarCallSignalEvent',
                'RallarCallSignalKind',
                'RallarCallSignalListener',
                'RallarCallSignalPayload',
                'RallarCallSignalSend',
                'RallarCallStartInput',
                'RallarCallState',
                'RallarCallStatus',
                'RallarCallsFacade',
                'RallarCameraSourceStartOptions',
                'RallarIncomingCallInvite',
                'RallarMediaFacade',
                'RallarMediaSourceAttachOptions',
                'RallarMediaSourceController',
                'RallarMediaSourceHandle',
                'RallarMediaSourceKind',
                'RallarMediaSourceState',
                'RallarMediaSourceStatus',
                'RallarMediaSourcesFacade',
                'RallarMicrophoneSourceStartOptions',
                'RallarRemoteStream',
                'RallarScreenSourceStartOptions',
                'RallarUnsubscribe'
            ],
            starExports: [],
            namespaceExports: []
        }
    },
    {
        filePath: 'packages/shared-web/browser/rallar-data.ts',
        expected: {
            values: [
                'createRallarDataFacade',
                'defineRallarDataStore'
            ],
            types: [
                'CreateRallarDataFacadeInput',
                'RallarDataChangeEvent',
                'RallarDataChangeListener',
                'RallarDataDurability',
                'RallarDataFacade',
                'RallarDataHydration',
                'RallarDataMigration',
                'RallarDataMigrationContext',
                'RallarDataScope',
                'RallarDataStorageEstimate',
                'RallarDataStore',
                'RallarDataStoreDefinition',
                'RallarDataStoreOptions',
                'RallarUnsubscribe'
            ],
            starExports: [],
            namespaceExports: []
        }
    },
    {
        filePath: 'packages/shared-web/browser/rallar-crdt.ts',
        expected: {
            values: ['createRallarCrdtFacade'],
            types: [
                'RallarCrdtCounterAddInput',
                'RallarCrdtDocument',
                'RallarCrdtFacade',
                'RallarCrdtFacadeDefaults',
                'RallarCrdtFacadeOptions',
                'RallarCrdtHttpCatchUpClient',
                'RallarCrdtNumberMergeInput',
                'RallarCrdtNumericMutationOptions',
                'RallarCrdtOpenOptions',
                'RallarCrdtOpenScope',
                'RallarCrdtSequenceDeleteInput',
                'RallarCrdtSequenceInsertInput',
                'RallarCrdtSequenceMoveInput',
                'RallarCrdtSequenceMutationOptions',
                'RallarCrdtSnapshotListener',
                'RallarCrdtUndoRedoGroupInput'
            ],
            starExports: [],
            namespaceExports: []
        }
    },
    {
        filePath: 'packages/shared-web/game/mod.ts',
        resolveStarExports: true,
        expected: {
            values: [
                'DEFAULT_RALLAR_GAME_CAPABILITY_TTL_MS',
                'DEFAULT_RALLAR_GAME_LANE_IDS',
                'RALLAR_GAME_CANNOT_HOST_SCORE',
                'RALLAR_GAME_MISSING_CAPABILITY_SCORE',
                'RallarGameAuthorityClient',
                'createRallarAuthorityBrowserMatch',
                'createRallarBrowserMatch',
                'createRallarGameEnvelope',
                'createRallarGameLanePresets',
                'createRallarGameMatch',
                'createRallarGameSequenceTracker',
                'deriveRallarGameDiagnostics',
                'electRallarGameHost',
                'isRallarGameEnvelope',
                'resolveRallarGameLaneIds',
                'resolveRallarGameTypeIds',
                'scoreRallarGameHostCapability'
            ],
            types: [
                'RallarAuthorityBrowserMatchConfig',
                'RallarAuthorityBrowserMatchDependencies',
                'RallarAuthorityBrowserMatchHandle',
                'RallarBrowserMatchConfig',
                'RallarBrowserMatchDependencies',
                'RallarBrowserMatchHandle',
                'RallarGameAuthorityClientConfig',
                'RallarGameAuthorityClientHandle',
                'RallarGameAuthorityClientRallarFacade',
                'RallarGameAuthorityCommandOptions',
                'RallarGameAuthorityPeerAssistOptions',
                'RallarGameCapabilityMessage',
                'RallarGameDiagnostics',
                'RallarGameDiagnosticsInput',
                'RallarGameDirectorAppointmentContext',
                'RallarGameDirectorAppointmentDiagnostics',
                'RallarGameDirectorAppointmentEligibility',
                'RallarGameDirectorAppointmentEligibilityStatus',
                'RallarGameDirectorAppointmentPolicy',
                'RallarGameDirectorAuthority',
                'RallarGameEgressState',
                'RallarGameEgressStatus',
                'RallarGameEnvelope',
                'RallarGameEnvelopeCreateInput',
                'RallarGameEnvelopeHandler',
                'RallarGameEnvelopeKind',
                'RallarGameEnvelopeRejectReason',
                'RallarGameHostAppointResult',
                'RallarGameHostCandidate',
                'RallarGameHostCandidateReason',
                'RallarGameHostCapability',
                'RallarGameHostElectionInput',
                'RallarGameHostElectionResult',
                'RallarGameHostLease',
                'RallarGameLaneIds',
                'RallarGameLanePresetBuilder',
                'RallarGameLanePresetOptions',
                'RallarGameLaneReadyOptions',
                'RallarGameMatchConfig',
                'RallarGameMatchHandle',
                'RallarGameMatchPhase',
                'RallarGameMatchStatus',
                'RallarGamePeerReadiness',
                'RallarGamePresenceSendOptions',
                'RallarGameRallarFacade',
                'RallarGameRecoveryState',
                'RallarGameRuntimeRelay',
                'RallarGameSendResult',
                'RallarGameSequenceAcceptConstraints',
                'RallarGameSequenceAcceptResult',
                'RallarGameSequenceTracker',
                'RallarGameStatusHandler',
                'RallarGameTypeIds',
                'RallarServerGameAuthorityRef'
            ],
            starExports: [
                './authority-match-support.ts',
                './diagnostics.ts',
                './election.ts',
                './envelopes.ts',
                './lanes.ts',
                './match-support.ts',
                './match.ts',
                './rallar-game-authority-client-contracts.ts',
                './rallar-game-authority-client.ts',
                './types.ts'
            ],
            namespaceExports: []
        }
    },
    {
        filePath: 'packages/shared-web/browser/api/state-mutation-http-contracts.ts',
        expected: {
            values: [],
            types: [
                'AcceptStateGroupInviteBody',
                'AppointStateGroupDirectorBody',
                'BanStateGroupMemberBody',
                'ConnectStateClientSessionBody',
                'ConnectStateGroupPresenceSessionBody',
                'CreateStateGroupBody',
                'CreateStateGroupInviteBody',
                'DisconnectStateGroupPresenceSessionBody',
                'HeartbeatStateClientSessionBody',
                'HeartbeatStateGroupPresenceSessionBody',
                'JoinStateGroupBody',
                'PutStateGroupTopologyConfigBody',
                'PutStateGroupTopologyOverrideBody',
                'ReconfigureStateGroupTopologyBody',
                'RemoveStateGroupMemberBody',
                'RevokeStateGroupInviteBody',
                'RotateStateGroupJoinCodeBody',
                'SetStateGroupMemberRoleBody',
                'TransferStateGroupOwnershipBody',
                'UnbanStateGroupMemberBody',
                'UpdateStateGroupBody',
                'UpsertStateGroupMemberBody'
            ],
            starExports: [],
            namespaceExports: []
        }
    },
    {
        filePath: 'packages/shared-web/browser/state-read/point-read.ts',
        expected: {
            values: ['readStateClientSnapshot', 'readStateGroupSnapshot'],
            types: [
                'ReadStateClientSnapshotOptions',
                'ReadStateGroupSnapshotOptions',
                'StateClientSnapshotRead',
                'StateGroupSnapshotRead'
            ],
            starExports: [],
            namespaceExports: []
        }
    },
    {
        filePath: 'packages/shared-web/browser/state-read/diagnostics.ts',
        expected: {
            values: [
                'emitBrowserStateReadDiagnostic',
                'setBrowserStateReadDiagnosticsSink'
            ],
            types: [
                'BrowserStateReadDiagnosticEvent',
                'BrowserStateReadDiagnosticsSink'
            ],
            starExports: [],
            namespaceExports: []
        }
    },
    {
        filePath: 'packages/shared-web/mod.ts',
        expected: {
            values: [
                'DEFAULT_STATE_HEARTBEAT_TTL_MSECS',
                'acceptStateGroupInvite',
                'appointStateGroupDirector',
                'archiveStateGroup',
                'banStateGroupMember',
                'createAndJoinStateGroup',
                'createStateGroupInvite',
                'deleteStateGroup',
                'joinStateGroup',
                'leaveStateGroup',
                'refreshStateHeartbeat',
                'refreshStateSnapshots',
                'removeStateGroupMember',
                'revokeStateGroupInvite',
                'rotateStateGroupJoinCode',
                'setStateGroupMemberRole',
                'transferStateGroupOwnership',
                'unbanStateGroupMember',
                'updateStateGroupDetails',
                'updateStateGroupMetadata'
            ],
            types: [
                'AcceptStateGroupInviteWorkflowInput',
                'ApiMutationRequestOptions',
                'ApiRequestOptions',
                'AppointRoomDirectorInput',
                'BanStateGroupMemberWorkflowInput',
                'CreateAndJoinStateGroupInput',
                'CreateStateGroupInviteWorkflowInput',
                'JoinStateGroupInput',
                'LeaveStateGroupInput',
                'RefreshStateHeartbeatOptions',
                'RefreshStateHeartbeatResult',
                'RemoveStateGroupMemberWorkflowInput',
                'RevokeStateGroupInviteWorkflowInput',
                'RoomLifecycleWorkflowInput',
                'RotateStateGroupJoinCodeWorkflowInput',
                'SetStateGroupMemberRoleWorkflowInput',
                'StateGroupWorkflowValue',
                'StateHeartbeatWorkflowValue',
                'StateSnapshots',
                'StateSnapshotsWorkflowValue',
                'TransferStateGroupOwnershipWorkflowInput',
                'UnbanStateGroupMemberWorkflowInput',
                'UpdateStateGroupDetailsInput',
                'UpdateStateGroupMetadataInput'
            ],
            starExports: [
                './browser/api-client-config.ts',
                './browser/api/http-error.ts',
                './browser/api/state-http-path.ts',
                './browser/api/state-mutation-http-contracts.ts',
                './browser/app-context.ts',
                './browser/auth/agent-session-ticket-http-api.ts',
                './browser/auth/session-http-api.ts',
                './browser/auth/websocket-ticket-http-api.ts',
                './browser/browser-al-runtime-stores.ts',
                './browser/browser-cache-repositories.ts',
                './browser/browser-queuebox.ts',
                './browser/connection/connection-http-api.ts',
                './browser/crdt/crdt-catch-up-http-api.ts',
                './browser/heartbeat.ts',
                './browser/middleware.ts',
                './browser/rallar-ai.ts',
                './browser/rallar-crdt-transport.ts',
                './browser/rallar-crdt.ts',
                './browser/rallar.ts',
                './browser/resilience-config.ts',
                './browser/rooms/room-group-state-http-api.ts',
                './browser/rtc-engine.ts',
                './browser/rtc-message-router.ts',
                './browser/rtc/rtc-topology-http-api.ts',
                './browser/session/client-session-http-api.ts',
                './browser/state-read/diagnostics.ts',
                './browser/state-read/point-read.ts',
                './browser/state-read/state-event-http-api.ts',
                './browser/state-read/state-snapshot-http-api.ts',
                './browser/stats/rallar-stats-http-api.ts',
                './browser/ws-message-router.ts',
                './game/mod.ts'
            ],
            namespaceExports: [
                'qboxEngine from ./browser/qbox-engine.ts',
                'wsEngine from ./browser/ws-engine.ts'
            ]
        }
    }
];

describe('shared-web public API snapshots', () => {
    for (const surface of PUBLIC_SURFACES) {
        it(`keeps ${surface.filePath} exports intentional`, () => {
            expect(
                collectExportSnapshot(surface.filePath, {
                    resolveStarExports: surface.resolveStarExports === true
                })
            ).toEqual(surface.expected);
        });
    }
});
