export const ROOM_ROAM_WALK_SPEED = 3.35;
export const ROOM_ROAM_SPRINT_SPEED = 5.75;
export const ROOM_ROAM_INSPECTION_SPEED_MULTIPLIER = 0.45;

export const REMOTE_RTC_POSITION_LERP_MS = 22;
export const REMOTE_SNAPSHOT_POSITION_LERP_MS = 60;

export const RELIC_MOTION_SEND_CADENCE_MS = 33;
export const RELIC_MOTION_IDLE_CADENCE_MS = 150;
export const RELIC_MOTION_FORCE_SEND_AFTER_MS = 180;
export const RELIC_MOTION_MIN_POSITION_DELTA = 0.025;
export const RELIC_MOTION_MIN_ROTATION_DELTA = 0.035;
export const RELIC_MOTION_DEFAULT_DELAY_MS = 75;
export const RELIC_MOTION_MIN_DELAY_MS = 45;
export const RELIC_MOTION_MAX_DELAY_MS = 140;
export const RELIC_MOTION_MAX_EXTRAPOLATION_MS = 150;

export const AVATAR_CAMERA_FOLLOW_HOLD_MS = 1100;
export const AVATAR_CAMERA_ZOOM_OUT_MS = 2600;
export const ROOM_FLYOVER_DURATION_MS = 4800;

export const AVATAR_ARRIVAL_SETTLE_MS = 420;
export const AVATAR_MOVING_STEP_CYCLE_MS = 82;
