import fs from 'node:fs/promises';
import path from 'node:path';

import {
  extractCommandTypesWithOptionalFields,
  scanDiscouragedServiceNames,
  scanFunctionInputContracts,
  scanOutputContractNaming,
  scanPlainObjectTypeAliases,
} from './contract-rules.mjs';
import { scanBoundaryUnknownFindings } from './boundary-unknown-findings.mjs';
import { scanConstructionRules } from './construction-rules.mjs';
import {
  estimateCyclomaticComplexity,
  extractRouteHandlerRanges,
  scanFactoryDefaults,
  scanFactorySpacing,
} from './factory-route-rules.mjs';
import { extractCreateFactories, extractFunctionSignatures } from './function-analysis.mjs';
import { isLayoutTypeScriptFile, layoutRuleIds, scanRepositoryLayout } from './layout-rules.mjs';
import { lineFromOffset, lineOffsets } from './source-text.mjs';
import { scanTypeOrganizationFindings } from './type-organization-rules.mjs';

const checkedExtensions = new Set(['.ts', '.tsx', '.d.ts', '.mts', '.cts', '.mjs']);
const outputContractExtensions = new Set(['.ts', '.tsx', '.mts', '.cts']);
const skippedDirectoryNames = new Set([
  '.git',
  '.deno',
  '.next',
  '.turbo',
  '.parcel-cache',
  'node_modules',
  'dist',
  'build',
  'coverage',
  'tmp',
  'tmp-media',
  '.nx',
  '.cache',
  '.husky',
  '.vscode',
  '.github',
  '.idea',
  'out',
]);
const nonProductionPathParts = new Set([
  'test',
  'tests',
  '__tests__',
  'mock',
  'mocks',
  '__mocks__',
  'fixture',
  '__fixtures__',
  'fixtures',
  'stories',
  'generated',
  'generated-types',
  'generated_types',
  'autogen',
  '.generated',
  '__generated__',
]);
const generatedPathPartPattern = new RegExp(
  '(^|[-_.])generated([-_.]|$)|^auto-generated$|^autogenerated$|' +
    '^codegen$|^\\.codegen$|^generated-code$',
  'u',
);
const testRunnerNames = ['playwright', 'vitest', 'jest', 'cypress'];
const testRunnerConfigExtensions = new Set([
  'ts',
  'tsx',
  'js',
  'jsx',
  'mts',
  'mtsx',
  'cts',
  'ctsx',
  'mjs',
  'mjsx',
  'cjs',
  'cjsx',
]);
const limits = {
  fileLineCount: 400,
  lineWidth: 100,
  handlerLineCount: 30,
  handlerComplexity: 8,
  factoryBlockLineCount: 45,
  factoryDefaultFieldMinimum: 2,
  factoryOptionalFieldMinimum: 3,
  functionArgumentCount: 3,
};
const defaultLayoutRuleIds = [
  layoutRuleIds.directoryDensity,
  layoutRuleIds.featurePrefixCluster,
  layoutRuleIds.filenameStyle,
  layoutRuleIds.genericFilename,
  layoutRuleIds.genericRouteInit,
  layoutRuleIds.unapprovedMod,
];
const detailedLayoutRuleIds = [
  layoutRuleIds.primaryExportName,
  layoutRuleIds.browserRoomBoundary,
  layoutRuleIds.serverGroupStateVocabulary,
];

export const activeLayoutRuleIds = (includeDetails) =>
  [...defaultLayoutRuleIds, ...(includeDetails ? detailedLayoutRuleIds : [])].toSorted();

export async function resolveScanRoots(candidates) {
  const existingRoots = [];
  for (const candidate of candidates) {
    try {
      const stat = await fs.stat(candidate);
      if (stat.isDirectory()) {
        existingRoots.push(candidate);
      }
    } catch {
      // Missing optional roots are ignored so the checker supports partial checkouts.
    }
  }
  return existingRoots;
}

export async function collectProductionSources(scanRoots) {
  const nestedFiles = await Promise.all(scanRoots.map(collectSourceFiles));
  const productionFiles = nestedFiles.flat().filter(isProductionCodeFile).sort();
  return Promise.all(
    productionFiles.map(async (file) => ({ file, raw: await fs.readFile(file, 'utf8') })),
  );
}

export function isTestRunnerConfigFile(base) {
  const configMarker = '.config.';
  const configMarkerIndex = base.lastIndexOf(configMarker);
  if (configMarkerIndex <= 0) {
    return false;
  }

  const extension = base.slice(configMarkerIndex + configMarker.length);
  if (!testRunnerConfigExtensions.has(extension)) {
    return false;
  }

  const stem = base.slice(0, configMarkerIndex);
  return testRunnerNames.some((runnerName) => isTestRunnerConfigStem(stem, runnerName));
}

export function scanProductionSources(input) {
  const layoutSources = input.sources.filter(({ file }) => isLayoutTypeScriptFile(file));
  const layoutResult = scanRepositoryLayout({
    repoRoot: input.repoRoot,
    sources: layoutSources,
    includeDetails: input.options.layoutDetails,
  });
  const findings = [];

  if (!input.options.layoutOnly) {
    for (const source of input.sources) {
      findings.push(
        ...scanFile(source, input.options).map((finding) => ({
          ...finding,
          file: source.file,
          kind: 'warn',
        })),
      );
    }
  }
  findings.push(...layoutResult.findings);
  return { findings, layoutCounts: layoutResult.counts };
}

function scanFile(source, options) {
  const { file, raw } = source;
  const findings = [];
  const sourceText = { file, raw, lines: raw.split('\n') };
  addFileMeasurementFindings(findings, sourceText.lines);
  addRouteFindings(findings, raw);
  addContractAndFactoryFindings(findings, sourceText, options);
  findings.push(...scanBoundaryUnknownFindings(raw));
  if (!isAmbientDeclarationFile(file)) {
    findings.push(...scanTypeOrganizationFindings(raw));
  }
  findings.push(...scanConstructionRules({ file, raw }, { details: options.constructionDetails }));
  return findings;
}

function isAmbientDeclarationFile(file) {
  return /\.d\.[cm]?ts$/u.test(file.toLowerCase());
}

function addFileMeasurementFindings(findings, lines) {
  if (lines.length > limits.fileLineCount) {
    findings.push(
      finding(
        'file.length',
        `File length ${lines.length} > ${limits.fileLineCount}; prefer a cohesive ` +
          'domain split. Route modules normally split by read/write/admin responsibility.',
      ),
    );
  }

  const longLines = lines
    .map((text, index) => ({ line: index + 1, text }))
    .filter((line) => line.text.length > limits.lineWidth);
  for (const line of longLines.slice(0, 8)) {
    findings.push(
      finding(
        'line.width',
        `Line ${line.line} exceeds ${limits.lineWidth} chars ` +
          `(actual ${line.text.length}). Prefer wrapped, traceable formatting.`,
      ),
    );
  }
  if (longLines.length > 8) {
    findings.push(
      finding('line.width', `... and ${longLines.length - 8} additional over-long lines.`),
    );
  }
}

function addRouteFindings(findings, raw) {
  const offsets = lineOffsets(raw);
  for (const range of extractRouteHandlerRanges(raw)) {
    const startLine = lineFromOffset(offsets, range.start);
    const endLine = lineFromOffset(offsets, range.end);
    const handlerLineCount = endLine - startLine + 1;
    const handlerText = raw.slice(range.start, range.end);
    if (handlerLineCount > limits.handlerLineCount) {
      findings.push(
        finding(
          'route.handler-length',
          `Route handler starting line ${startLine} has ${handlerLineCount} lines ` +
            `(target <= ${limits.handlerLineCount}).`,
        ),
      );
    }
    const complexity = estimateCyclomaticComplexity(handlerText);
    if (complexity > limits.handlerComplexity) {
      findings.push(
        finding(
          'route.handler-complexity',
          `Route handler starting line ${startLine} has estimated complexity ` +
            `${complexity} (target <= ${limits.handlerComplexity}).`,
        ),
      );
    }
  }
}

function addContractAndFactoryFindings(findings, sourceText, options) {
  const { file, raw, lines } = sourceText;
  for (const commandType of extractCommandTypesWithOptionalFields(lines)) {
    const fields = commandType.fields.map((field) => field.text).join('; ');
    findings.push(
      finding(
        'contract.optional-command',
        `Command model ${commandType.name} contains optional fields, e.g. ${fields}. ` +
          'Keep request optionality in a separate request type and decode to required fields.',
      ),
    );
  }

  const functions = extractFunctionSignatures(raw);
  addMessages(
    findings,
    'function.input-contract',
    scanFunctionInputContracts(functions, limits.functionArgumentCount),
  );
  addMessages(findings, 'service.name', scanDiscouragedServiceNames(raw));
  if (options.outputContracts && outputContractExtensions.has(path.extname(file).toLowerCase())) {
    addMessages(findings, 'function.output-contract', scanOutputContractNaming(raw, functions));
  }
  if (options.objectInterfaces) {
    addMessages(findings, 'contract.object-interface', scanPlainObjectTypeAliases(raw));
  }

  for (const factory of extractCreateFactories(raw)) {
    addMessages(
      findings,
      'factory.spacing',
      scanFactorySpacing(raw, factory, limits.factoryBlockLineCount),
    );
    addMessages(
      findings,
      'factory.defaults',
      scanFactoryDefaults({
        raw,
        lines,
        factory,
        limits: {
          defaultFieldMinimum: limits.factoryDefaultFieldMinimum,
          optionalFieldMinimum: limits.factoryOptionalFieldMinimum,
        },
      }),
    );
  }
}

async function collectSourceFiles(current) {
  const files = [];
  const entries = await fs.readdir(current, { withFileTypes: true });
  for (const entry of entries) {
    const next = path.join(current, entry.name);
    if (entry.isDirectory()) {
      if (skippedDirectoryNames.has(entry.name) || entry.name.startsWith('.')) {
        continue;
      }
      files.push(...(await collectSourceFiles(next)));
    } else if (entry.isFile() && checkedExtensions.has(path.extname(entry.name).toLowerCase())) {
      files.push(next);
    }
  }
  return files;
}

export function isProductionCodeFile(file) {
  const normalized = file.replace(/\\/gu, '/').toLowerCase();
  const parts = normalized.split('/');
  if (!checkedExtensions.has(path.extname(normalized))) {
    return false;
  }
  if (
    parts.some(
      (part) => part && (nonProductionPathParts.has(part) || generatedPathPartPattern.test(part)),
    )
  ) {
    return false;
  }
  const base = parts[parts.length - 1];
  if (isTestRunnerConfigFile(base)) {
    return false;
  }
  if (
    /\.generated(?:\.d)?\.[cm]?(?:t|j)sx?$/u.test(base) ||
    /\.gen(?:\.d)?\.[cm]?(?:t|j)sx?$/u.test(base) ||
    /\.pb(?:\.d)?\.[cm]?(?:t|j)sx?$/u.test(base)
  ) {
    return false;
  }
  return !/[\w-]+\.(?:test|spec|mock|fixture|stories)\.(?:d\.[cm]?ts|[cm]ts|tsx|jsx|js)$/u.test(
    base,
  );
}

function isTestRunnerConfigStem(stem, runnerName) {
  if (stem === runnerName) {
    return true;
  }
  if (!stem.startsWith(runnerName)) {
    return false;
  }

  const qualifier = stem.slice(runnerName.length);
  if (qualifier[0] !== '.' && qualifier[0] !== '-') {
    return false;
  }
  return qualifier.slice(1).split('.').every(isTestRunnerQualifierSegment);
}

function isTestRunnerQualifierSegment(segment) {
  return segment.length > 0 && [...segment].every(isTestRunnerQualifierCharacter);
}

function isTestRunnerQualifierCharacter(character) {
  return (
    (character >= 'a' && character <= 'z') ||
    (character >= '0' && character <= '9') ||
    character === '_' ||
    character === '-'
  );
}

function addMessages(findings, ruleId, messages) {
  findings.push(...messages.map((message) => finding(ruleId, message)));
}
function finding(ruleId, message, symbol) {
  return { ruleId, message, symbol };
}
