import fs from 'node:fs/promises';
import path from 'node:path';

import {
  extractCommandTypesWithOptionalFields,
  findUnknownUsages,
  scanDiscouragedServiceNames,
  scanFunctionInputContracts,
  scanOutputContractNaming,
  scanPlainObjectTypeAliases,
} from './contract-rules.mjs';
import {
  estimateCyclomaticComplexity,
  extractRouteHandlerRanges,
  scanFactoryDefaults,
  scanFactorySpacing,
} from './factory-route-rules.mjs';
import { extractCreateFactories, extractFunctionSignatures } from './function-analysis.mjs';
import {
  isLayoutTypeScriptFile,
  layoutRuleIds,
  scanRepositoryLayout,
} from './layout-rules.mjs';
import { lineFromOffset, lineOffsets } from './source-text.mjs';

const checkedExtensions = new Set(['.ts', '.tsx', '.d.ts', '.mts', '.cts', '.mjs']);
const skippedDirectoryNames = new Set([
  '.git',
  '.deno',
  '.next',
  '.turbo',
  '.parcel-cache',
  'node_modules',
  'dist',
  'build',
  'coverage',
  'tmp',
  'tmp-media',
  '.nx',
  '.cache',
  '.husky',
  '.vscode',
  '.github',
  '.idea',
  'out',
]);
const nonProductionPathParts = new Set([
  'test',
  'tests',
  '__tests__',
  'mock',
  'mocks',
  '__mocks__',
  'fixture',
  '__fixtures__',
  'fixtures',
  'stories',
  'generated',
  'generated-types',
  'generated_types',
  'autogen',
  '.generated',
  '__generated__',
]);
const generatedPathPartPattern = new RegExp(
  '(^|[-_.])generated([-_.]|$)|^auto-generated$|^autogenerated$|' +
    '^codegen$|^\\.codegen$|^generated-code$',
  'u',
);
const testRunnerConfigPattern =
  /^(?:playwright|vitest|jest|cypress)(?:[.-][a-z0-9_-]+)*\.config\.[cm]?[jt]sx?$/u;
const limits = {
  fileLineCount: 400,
  lineWidth: 100,
  handlerLineCount: 30,
  handlerComplexity: 8,
  factoryBlockLineCount: 45,
  factoryDefaultFieldMinimum: 2,
  factoryOptionalFieldMinimum: 3,
  functionArgumentCount: 3,
};
const defaultLayoutRuleIds = [
  layoutRuleIds.directoryDensity,
  layoutRuleIds.featurePrefixCluster,
  layoutRuleIds.filenameStyle,
  layoutRuleIds.genericFilename,
  layoutRuleIds.genericRouteInit,
  layoutRuleIds.unapprovedMod,
];
const detailedLayoutRuleIds = [
  layoutRuleIds.primaryExportName,
  layoutRuleIds.browserRoomBoundary,
  layoutRuleIds.serverGroupStateVocabulary,
];

export const activeLayoutRuleIds = (includeDetails) =>
  [
    ...defaultLayoutRuleIds,
    ...(includeDetails ? detailedLayoutRuleIds : []),
  ].toSorted();

export async function resolveScanRoots(candidates) {
  const existingRoots = [];
  for (const candidate of candidates) {
    try {
      const stat = await fs.stat(candidate);
      if (stat.isDirectory()) {
        existingRoots.push(candidate);
      }
    } catch {
      // Missing optional roots are ignored so the checker supports partial checkouts.
    }
  }
  return existingRoots;
}

export async function collectProductionSources(scanRoots) {
  const nestedFiles = await Promise.all(scanRoots.map(collectSourceFiles));
  const productionFiles = nestedFiles.flat().filter(isProductionCodeFile).sort();
  return Promise.all(
    productionFiles.map(async (file) => ({ file, raw: await fs.readFile(file, 'utf8') })),
  );
}

export function scanProductionSources(input) {
  const layoutSources = input.sources.filter(({ file }) => isLayoutTypeScriptFile(file));
  const layoutResult = scanRepositoryLayout({
    repoRoot: input.repoRoot,
    sources: layoutSources,
    includeDetails: input.options.layoutDetails,
  });
  const findings = [];

  if (!input.options.layoutOnly) {
    for (const source of input.sources) {
      findings.push(
        ...scanFile(source.raw, input.options).map((finding) => ({
          ...finding,
          file: source.file,
          kind: 'warn',
        })),
      );
    }
  }
  findings.push(...layoutResult.findings);
  return { findings, layoutCounts: layoutResult.counts };
}

function scanFile(raw, options) {
  const findings = [];
  const lines = raw.split('\n');
  const offsets = lineOffsets(raw);

  if (lines.length > limits.fileLineCount) {
    findings.push(
      finding(
        'file.length',
        `File length ${lines.length} > ${limits.fileLineCount}; prefer a cohesive ` +
          'domain split. Route modules normally split by read/write/admin responsibility.',
      ),
    );
  }

  const longLines = lines
    .map((text, index) => ({ line: index + 1, text }))
    .filter((line) => line.text.length > limits.lineWidth);
  for (const line of longLines.slice(0, 8)) {
    findings.push(
      finding(
        'line.width',
        `Line ${line.line} exceeds ${limits.lineWidth} chars ` +
          `(actual ${line.text.length}). Prefer wrapped, traceable formatting.`,
      ),
    );
  }
  if (longLines.length > 8) {
    findings.push(
      finding('line.width', `... and ${longLines.length - 8} additional over-long lines.`),
    );
  }

  for (const range of extractRouteHandlerRanges(raw)) {
    const startLine = lineFromOffset(offsets, range.start);
    const endLine = lineFromOffset(offsets, range.end);
    const handlerLineCount = endLine - startLine + 1;
    const handlerText = raw.slice(range.start, range.end);
    if (handlerLineCount > limits.handlerLineCount) {
      findings.push(
        finding(
          'route.handler-length',
          `Route handler starting line ${startLine} has ${handlerLineCount} lines ` +
            `(target <= ${limits.handlerLineCount}).`,
        ),
      );
    }
    const complexity = estimateCyclomaticComplexity(handlerText);
    if (complexity > limits.handlerComplexity) {
      findings.push(
        finding(
          'route.handler-complexity',
          `Route handler starting line ${startLine} has estimated complexity ` +
            `${complexity} (target <= ${limits.handlerComplexity}).`,
        ),
      );
    }
  }

  for (const commandType of extractCommandTypesWithOptionalFields(lines)) {
    const fields = commandType.fields.map((field) => field.text).join('; ');
    findings.push(
      finding(
        'contract.optional-command',
        `Command model ${commandType.name} contains optional fields, e.g. ${fields}. ` +
          'Keep request optionality in a separate request type and decode to required fields.',
      ),
    );
  }

  const functions = extractFunctionSignatures(raw);
  addMessages(
    findings,
    'function.input-contract',
    scanFunctionInputContracts(functions, limits.functionArgumentCount),
  );
  addMessages(findings, 'service.name', scanDiscouragedServiceNames(raw));
  if (options.outputContracts) {
    addMessages(findings, 'function.output-contract', scanOutputContractNaming(raw, functions));
  }
  if (options.objectInterfaces) {
    addMessages(findings, 'contract.object-interface', scanPlainObjectTypeAliases(raw));
  }

  for (const factory of extractCreateFactories(raw)) {
    addMessages(
      findings,
      'factory.spacing',
      scanFactorySpacing(raw, factory, limits.factoryBlockLineCount),
    );
    addMessages(
      findings,
      'factory.defaults',
      scanFactoryDefaults({
        raw,
        lines,
        factory,
        limits: {
          defaultFieldMinimum: limits.factoryDefaultFieldMinimum,
          optionalFieldMinimum: limits.factoryOptionalFieldMinimum,
        },
      }),
    );
  }

  const unknownUsages = findUnknownUsages(lines);
  for (const usage of unknownUsages.slice(0, 5)) {
    findings.push(
      finding(
        'boundary.unknown',
        `Review unknown at line ${usage.line}: ${usage.text} ` +
          'Keep it at an untrusted boundary and normalize it before domain logic.',
      ),
    );
  }
  if (unknownUsages.length > 5) {
    findings.push(
      finding(
        'boundary.unknown',
        `... and ${unknownUsages.length - 5} additional unknown occurrences. ` +
          'Reduce unknown propagation at domain boundaries.',
      ),
    );
  }
  return findings;
}

async function collectSourceFiles(current) {
  const files = [];
  const entries = await fs.readdir(current, { withFileTypes: true });
  for (const entry of entries) {
    const next = path.join(current, entry.name);
    if (entry.isDirectory()) {
      if (skippedDirectoryNames.has(entry.name) || entry.name.startsWith('.')) {
        continue;
      }
      files.push(...(await collectSourceFiles(next)));
    } else if (entry.isFile() && checkedExtensions.has(path.extname(entry.name).toLowerCase())) {
      files.push(next);
    }
  }
  return files;
}

export function isProductionCodeFile(file) {
  const normalized = file.replace(/\\/gu, '/').toLowerCase();
  const parts = normalized.split('/');
  if (
    parts.some(
      (part) => part && (nonProductionPathParts.has(part) || generatedPathPartPattern.test(part)),
    )
  ) {
    return false;
  }
  const base = parts[parts.length - 1];
  if (testRunnerConfigPattern.test(base)) {
    return false;
  }
  if (
    /\.generated(?:\.d)?\.[cm]?(?:t|j)sx?$/u.test(base) ||
    /\.gen(?:\.d)?\.[cm]?(?:t|j)sx?$/u.test(base) ||
    /\.pb(?:\.d)?\.[cm]?(?:t|j)sx?$/u.test(base)
  ) {
    return false;
  }
  return !/[\w-]+\.(?:test|spec|mock|fixture|stories)\.(?:d\.[cm]?ts|[cm]ts|tsx|jsx|js)$/u.test(
    base,
  );
}

function addMessages(findings, ruleId, messages) {
  findings.push(...messages.map((message) => finding(ruleId, message)));
}

function finding(ruleId, message) {
  return { ruleId, message };
}
