export interface MutationRouteInventoryRow {
  readonly transport: 'HTTP' | 'WS_INBOX' | 'WS_LIFECYCLE' | 'MAINTENANCE';
  readonly entrypoint: string;
  readonly type: string;
  readonly source: string;
  readonly registrationMarker: string;
  readonly enqueueSource: string;
  readonly enqueueMarker: string;
  readonly ownerSource: string;
  readonly owner: string;
  readonly typeOwnerSource?: string;
  readonly dispatchSource?: string;
  readonly operationDiscriminant?: string;
  readonly familyRegistrationMarker?: string;
  readonly rootSource?: string;
  readonly constructionRootMarker?: string;
  readonly familyOwnerOrder?: number;
}

export const MUTATION_ROUTE_OWNER_PATHS = {
  C: 'packages/shared-server/rallar-system/client-state/inbox/app-client-inbox-service.ts',
  X: 'packages/shared-server/rallar-system/client-state/inbox/client-state-inbox-handler.ts',
  G: 'packages/shared-server/rallar-system/services/AppGroupInboxService.ts',
  I: 'packages/shared-server/rallar-system/group-state/inbox/group-state-inbox-contracts.ts',
  H: 'packages/shared-server/rallar-system/group-state/inbox/group-state-inbox-handler.ts',
  P: 'packages/shared-server/rallar-system/group-state/presence/group-presence-service.ts',
  T: 'packages/shared-server/rallar-system/topology/inbox/topology-app-inbox-handler.ts',
  R: 'packages/shared-server/rallar-system/rtc-topology/inbox/rtc-rtt-app-inbox-handler.ts',
  A: 'packages/shared-server/rallar-system/auth/inbox/app-auth-inbox-service.ts',
  B: 'packages/shared-server/rallar-system/auth/inbox/auth-inbox-handler.ts',
  D: 'packages/shared-server/rallar-system/crdt/inbox/app-crdt-inbox-service.ts',
  N: 'packages/shared-server/rallar-system/admin-operations/inbox/app-admin-inbox-service.ts',
} as const;

export const MUTATION_ROUTE_OWNER_DISPATCH_PATHS = {
  'AppAdminInboxService.processCommand': 'processCommand',
  'AuthInboxHandler.processAuthMutation': 'authInboxHandler.processAuthMutation',
  'AppClientInboxService.processAuthorisedWsConnect': 'processAuthorisedWsConnect',
  'AppClientInboxService.processAuthorisedWsDisconnect': 'processAuthorisedWsDisconnect',
  'AppClientInboxService.processCommand': 'processCommand',
  'AppClientInboxService.processExpiredSessionCommands': 'processExpiredSessionCommands',
  'ClientStateInboxHandler.processAuthorisedWsConnect': 'handler.processAuthorisedWsConnect',
  'ClientStateInboxHandler.processAuthorisedWsDisconnect': 'handler.processAuthorisedWsDisconnect',
  'ClientStateInboxHandler.processCommand': 'handler.processCommand',
  'ClientStateInboxHandler.processExpiredSessionCommands': 'handler.processExpiredSessionCommands',
  'AppCrdtInboxService.processCommand': 'processCommand',
  'GroupStateInboxHandler.processGroupStateMutation':
    'groupStateInboxHandler.processGroupStateMutation',
  'RtcRttAppInboxHandler.processMutation': 'rtcRttAppInboxHandler.processMutation',
  'TopologyAppInboxHandler.processMutation': 'topologyAppInboxHandler.processMutation',
  processGroupSessionCleanup: 'processGroupSessionCleanup',
} as const;

const CLIENT_ROUTE = '/api/state/apps/:applicationId/workspaces/:workspaceId/clients';
const CLIENT_INSTANCE_ROUTE = `${CLIENT_ROUTE}/:principalId/instances/:clientInstanceId`;
const CLIENT_SESSION_ROUTE = `${CLIENT_INSTANCE_ROUTE}/sessions/:sessionId`;
const GROUP_ROUTE = '/api/state/apps/:applicationId/workspaces/:workspaceId/groups';
const GROUP_ITEM_ROUTE = `${GROUP_ROUTE}/:groupId`;
const TOPOLOGY_ROUTE = `${GROUP_ITEM_ROUTE}/topology`;

export const MUTATION_ROUTE_INVENTORY_ROWS: readonly MutationRouteInventoryRow[] = [
  {
    transport: 'HTTP',
    entrypoint: `PUT ${CLIENT_ROUTE}/:principalId/principal`,
    type: 'CLIENT_PRINCIPAL_UPSERT',
    source: 'c',
    registrationMarker: '/clients/:principalId/principal',
    enqueueSource: 'c',
    enqueueMarker: 'processClientAppInbox',
    ownerSource: 'X',
    owner: 'ClientStateInboxHandler.processCommand',
    typeOwnerSource: 'C',
    dispatchSource: 'C',
  },
  {
    transport: 'HTTP',
    entrypoint: `PUT ${CLIENT_INSTANCE_ROUTE}`,
    type: 'CLIENT_INSTANCE_UPSERT',
    source: 'c',
    registrationMarker: '/instances/:clientInstanceId',
    enqueueSource: 'c',
    enqueueMarker: 'processClientAppInbox',
    ownerSource: 'X',
    owner: 'ClientStateInboxHandler.processCommand',
    typeOwnerSource: 'C',
    dispatchSource: 'C',
  },
  {
    transport: 'HTTP',
    entrypoint: `PUT ${CLIENT_SESSION_ROUTE}`,
    type: 'CLIENT_SESSION_CONNECT',
    source: 'c',
    registrationMarker: '/sessions/:sessionId',
    enqueueSource: 'c',
    enqueueMarker: 'processClientAppInbox',
    ownerSource: 'X',
    owner: 'ClientStateInboxHandler.processCommand',
    typeOwnerSource: 'C',
    dispatchSource: 'C',
  },
  {
    transport: 'HTTP',
    entrypoint: `POST ${CLIENT_SESSION_ROUTE}/heartbeat`,
    type: 'CLIENT_SESSION_HEARTBEAT',
    source: 'c',
    registrationMarker: '/sessions/:sessionId/heartbeat',
    enqueueSource: 'c',
    enqueueMarker: 'processClientAppInbox',
    ownerSource: 'X',
    owner: 'ClientStateInboxHandler.processCommand',
    typeOwnerSource: 'C',
    dispatchSource: 'C',
  },
  {
    transport: 'HTTP',
    entrypoint: `POST ${CLIENT_SESSION_ROUTE}/disconnect`,
    type: 'CLIENT_SESSION_DISCONNECT',
    source: 'c',
    registrationMarker: '/sessions/:sessionId/disconnect',
    enqueueSource: 'c',
    enqueueMarker: 'processClientAppInbox',
    ownerSource: 'X',
    owner: 'ClientStateInboxHandler.processCommand',
    typeOwnerSource: 'C',
    dispatchSource: 'C',
  },
  {
    transport: 'HTTP',
    entrypoint: 'GET /api/ws/:sessionId upgrade',
    type: 'AUTH_WS_TICKET_CONSUME',
    source: 'w',
    registrationMarker: "'/api/ws/:sessionId'",
    enqueueSource: 'rq',
    enqueueMarker: 'requireSharedWsAuthSession',
    ownerSource: 'B',
    owner: 'AuthInboxHandler.processAuthMutation',
    typeOwnerSource: 'A',
    dispatchSource: 'A',
  },
  {
    transport: 'HTTP',
    entrypoint: 'GET /api/ws/:sessionId upgrade',
    type: 'CLIENT_AUTHORISED_WS_CONNECT',
    source: 'w',
    registrationMarker: "'/api/ws/:sessionId'",
    enqueueSource: 'w',
    enqueueMarker: 'enqueueAuthorisedWsClientConnect',
    ownerSource: 'X',
    owner: 'ClientStateInboxHandler.processAuthorisedWsConnect',
    typeOwnerSource: 'C',
    dispatchSource: 'C',
  },
  {
    transport: 'WS_LIFECYCLE',
    entrypoint: 'websocket onClose',
    type: 'CLIENT_AUTHORISED_WS_DISCONNECT',
    source: 'l',
    registrationMarker: 'onClose:',
    enqueueSource: 'l',
    enqueueMarker: 'enqueueClientSessionDisconnect',
    ownerSource: 'X',
    owner: 'ClientStateInboxHandler.processAuthorisedWsDisconnect',
    typeOwnerSource: 'C',
    dispatchSource: 'C',
  },
  {
    transport: 'MAINTENANCE',
    entrypoint: 'client session expiry reconciliation',
    type: 'CLIENT_EXPIRED_SESSIONS',
    source: 'e',
    registrationMarker: 'enqueuePresenceExpiryReconciliation',
    enqueueSource: 'e',
    enqueueMarker: 'enqueueExpiredSessions',
    ownerSource: 'X',
    owner: 'ClientStateInboxHandler.processExpiredSessionCommands',
    typeOwnerSource: 'C',
    dispatchSource: 'C',
  },
  {
    transport: 'HTTP',
    entrypoint: 'POST /api/auth/register',
    type: 'AUTH_USER_REGISTER',
    source: 'a',
    registrationMarker: "'/api/auth/register'",
    enqueueSource: 'a',
    enqueueMarker: 'registerUser',
    ownerSource: 'B',
    owner: 'AuthInboxHandler.processAuthMutation',
    typeOwnerSource: 'A',
    dispatchSource: 'A',
  },
  {
    transport: 'HTTP',
    entrypoint: 'POST /api/auth/login',
    type: 'AUTH_SESSION_ISSUE',
    source: 'a',
    registrationMarker: "'/api/auth/login'",
    enqueueSource: 'a',
    enqueueMarker: 'issueSession',
    ownerSource: 'B',
    owner: 'AuthInboxHandler.processAuthMutation',
    typeOwnerSource: 'A',
    dispatchSource: 'A',
  },
  {
    transport: 'HTTP',
    entrypoint: 'POST /api/auth/logout',
    type: 'AUTH_SESSION_LOGOUT',
    source: 'a',
    registrationMarker: "'/api/auth/logout'",
    enqueueSource: 'a',
    enqueueMarker: 'logoutSession',
    ownerSource: 'B',
    owner: 'AuthInboxHandler.processAuthMutation',
    typeOwnerSource: 'A',
    dispatchSource: 'A',
  },
  {
    transport: 'HTTP',
    entrypoint: 'POST /api/auth/ws-ticket',
    type: 'AUTH_WS_TICKET_ISSUE',
    source: 'a',
    registrationMarker: "'/api/auth/ws-ticket'",
    enqueueSource: 'a',
    enqueueMarker: 'issueWebSocketTicket',
    ownerSource: 'B',
    owner: 'AuthInboxHandler.processAuthMutation',
    typeOwnerSource: 'A',
    dispatchSource: 'A',
  },
  {
    transport: 'HTTP',
    entrypoint: 'POST /api/auth/agent-session-tickets',
    type: 'AUTH_AGENT_SESSION_TICKETS_ISSUE',
    source: 'a',
    registrationMarker: "'/api/auth/agent-session-tickets'",
    enqueueSource: 'a',
    enqueueMarker: 'issueAgentSessionTickets',
    ownerSource: 'B',
    owner: 'AuthInboxHandler.processAuthMutation',
    typeOwnerSource: 'A',
    dispatchSource: 'A',
  },
  {
    transport: 'HTTP',
    entrypoint: 'POST /api/auth/agent-session-tickets/consume',
    type: 'AUTH_AGENT_SESSION_TICKET_CONSUME',
    source: 'a',
    registrationMarker: "'/api/auth/agent-session-tickets/consume'",
    enqueueSource: 'a',
    enqueueMarker: 'consumeAgentSessionTicket',
    ownerSource: 'B',
    owner: 'AuthInboxHandler.processAuthMutation',
    typeOwnerSource: 'A',
    dispatchSource: 'A',
  },
  {
    transport: 'HTTP',
    entrypoint: `POST ${GROUP_ROUTE}`,
    type: 'GROUP_CREATE',
    source: 'gs',
    registrationMarker: 'registerCreateGroupRoute',
    enqueueSource: 'gc',
    enqueueMarker: 'AppInboxType.GROUP_CREATE',
    ownerSource: 'H',
    owner: 'GroupStateInboxHandler.processGroupStateMutation',
    typeOwnerSource: 'I',
    dispatchSource: 'G',
    operationDiscriminant: 'create-group',
    familyRegistrationMarker: 'registerGroupStateMutationRoutes',
    rootSource: 'gr',
    constructionRootMarker: 'registerGroupStateRoutes',
    familyOwnerOrder: 0,
  },
  {
    transport: 'HTTP',
    entrypoint: `PUT ${GROUP_ITEM_ROUTE}`,
    type: 'GROUP_UPDATE',
    source: 'gs',
    registrationMarker: 'registerUpdateGroupRoute',
    enqueueSource: 'gc',
    enqueueMarker: 'AppInboxType.GROUP_UPDATE',
    ownerSource: 'H',
    owner: 'GroupStateInboxHandler.processGroupStateMutation',
    typeOwnerSource: 'I',
    dispatchSource: 'G',
    operationDiscriminant: 'update-group',
    familyRegistrationMarker: 'registerGroupStateMutationRoutes',
    rootSource: 'gr',
    constructionRootMarker: 'registerGroupStateRoutes',
    familyOwnerOrder: 1,
  },
  {
    transport: 'HTTP',
    entrypoint: `POST ${GROUP_ITEM_ROUTE}/director/appoint`,
    type: 'GROUP_DIRECTOR_APPOINT',
    source: 'gs',
    registrationMarker: 'registerAppointGroupDirectorRoute',
    enqueueSource: 'gc',
    enqueueMarker: 'AppInboxType.GROUP_DIRECTOR_APPOINT',
    ownerSource: 'H',
    owner: 'GroupStateInboxHandler.processGroupStateMutation',
    typeOwnerSource: 'I',
    dispatchSource: 'G',
    operationDiscriminant: 'appoint-group-director',
    familyRegistrationMarker: 'registerGroupStateMutationRoutes',
    rootSource: 'gr',
    constructionRootMarker: 'registerGroupStateRoutes',
    familyOwnerOrder: 2,
  },
  {
    transport: 'HTTP',
    entrypoint: `POST ${GROUP_ITEM_ROUTE}/lifecycle/establish`,
    type: 'GROUP_ESTABLISHMENT_START',
    source: 'gs',
    registrationMarker: 'registerStartGroupEstablishmentRoute',
    enqueueSource: 'gc',
    enqueueMarker: 'AppInboxType.GROUP_ESTABLISHMENT_START',
    ownerSource: 'H',
    owner: 'GroupStateInboxHandler.processGroupStateMutation',
    typeOwnerSource: 'I',
    dispatchSource: 'G',
    operationDiscriminant: 'start-group-establishment',
    familyRegistrationMarker: 'registerGroupStateMutationRoutes',
    rootSource: 'gr',
    constructionRootMarker: 'registerGroupStateRoutes',
    familyOwnerOrder: 3,
  },
  {
    transport: 'HTTP',
    entrypoint: `POST ${GROUP_ITEM_ROUTE}/lifecycle/activate`,
    type: 'GROUP_ACTIVATE',
    source: 'gs',
    registrationMarker: 'registerActivateGroupRoute',
    enqueueSource: 'gc',
    enqueueMarker: 'AppInboxType.GROUP_ACTIVATE',
    ownerSource: 'H',
    owner: 'GroupStateInboxHandler.processGroupStateMutation',
    typeOwnerSource: 'I',
    dispatchSource: 'G',
    operationDiscriminant: 'activate-group',
    familyRegistrationMarker: 'registerGroupStateMutationRoutes',
    rootSource: 'gr',
    constructionRootMarker: 'registerGroupStateRoutes',
    familyOwnerOrder: 3,
  },
  {
    transport: 'HTTP',
    entrypoint: `POST ${GROUP_ITEM_ROUTE}/lifecycle/reopen`,
    type: 'GROUP_ESTABLISHMENT_REOPEN',
    source: 'gs',
    registrationMarker: 'registerReopenGroupEstablishmentRoute',
    enqueueSource: 'gc',
    enqueueMarker: 'AppInboxType.GROUP_ESTABLISHMENT_REOPEN',
    ownerSource: 'H',
    owner: 'GroupStateInboxHandler.processGroupStateMutation',
    typeOwnerSource: 'I',
    dispatchSource: 'G',
    operationDiscriminant: 'reopen-group-establishment',
    familyRegistrationMarker: 'registerGroupStateMutationRoutes',
    rootSource: 'gr',
    constructionRootMarker: 'registerGroupStateRoutes',
    familyOwnerOrder: 3,
  },
  {
    transport: 'HTTP',
    entrypoint: `POST ${GROUP_ITEM_ROUTE}/join`,
    type: 'GROUP_JOIN',
    source: 'ga',
    registrationMarker: 'registerJoinGroupRoute',
    enqueueSource: 'gc',
    enqueueMarker: 'AppInboxType.GROUP_JOIN',
    ownerSource: 'H',
    owner: 'GroupStateInboxHandler.processGroupStateMutation',
    typeOwnerSource: 'I',
    dispatchSource: 'G',
    operationDiscriminant: 'join-group',
    familyRegistrationMarker: 'registerGroupAdmissionRoutes',
    rootSource: 'gr',
    constructionRootMarker: 'registerGroupStateRoutes',
    familyOwnerOrder: 0,
  },
  {
    transport: 'HTTP',
    entrypoint: `POST ${GROUP_ITEM_ROUTE}/invites/:principalId`,
    type: 'GROUP_INVITE_CREATE',
    source: 'ga',
    registrationMarker: 'registerCreateGroupInviteRoute',
    enqueueSource: 'gc',
    enqueueMarker: 'AppInboxType.GROUP_INVITE_CREATE',
    ownerSource: 'H',
    owner: 'GroupStateInboxHandler.processGroupStateMutation',
    typeOwnerSource: 'I',
    dispatchSource: 'G',
    operationDiscriminant: 'create-group-invite',
    familyRegistrationMarker: 'registerGroupAdmissionRoutes',
    rootSource: 'gr',
    constructionRootMarker: 'registerGroupStateRoutes',
    familyOwnerOrder: 3,
  },
  {
    transport: 'HTTP',
    entrypoint: `POST ${GROUP_ITEM_ROUTE}/invites/:principalId/revoke`,
    type: 'GROUP_INVITE_REVOKE',
    source: 'ga',
    registrationMarker: 'registerRevokeGroupInviteRoute',
    enqueueSource: 'gc',
    enqueueMarker: 'AppInboxType.GROUP_INVITE_REVOKE',
    ownerSource: 'H',
    owner: 'GroupStateInboxHandler.processGroupStateMutation',
    typeOwnerSource: 'I',
    dispatchSource: 'G',
    operationDiscriminant: 'revoke-group-invite',
    familyRegistrationMarker: 'registerGroupAdmissionRoutes',
    rootSource: 'gr',
    constructionRootMarker: 'registerGroupStateRoutes',
    familyOwnerOrder: 4,
  },
  {
    transport: 'HTTP',
    entrypoint: `POST ${GROUP_ITEM_ROUTE}/invites/accept`,
    type: 'GROUP_INVITE_ACCEPT',
    source: 'ga',
    registrationMarker: 'registerAcceptGroupInviteRoute',
    enqueueSource: 'gc',
    enqueueMarker: 'AppInboxType.GROUP_INVITE_ACCEPT',
    ownerSource: 'H',
    owner: 'GroupStateInboxHandler.processGroupStateMutation',
    typeOwnerSource: 'I',
    dispatchSource: 'G',
    operationDiscriminant: 'accept-group-invite',
    familyRegistrationMarker: 'registerGroupAdmissionRoutes',
    rootSource: 'gr',
    constructionRootMarker: 'registerGroupStateRoutes',
    familyOwnerOrder: 1,
  },
  {
    transport: 'HTTP',
    entrypoint: `POST ${GROUP_ITEM_ROUTE}/join-code/rotate`,
    type: 'GROUP_JOIN_CODE_ROTATE',
    source: 'ga',
    registrationMarker: 'registerRotateGroupJoinCodeRoute',
    enqueueSource: 'gc',
    enqueueMarker: 'AppInboxType.GROUP_JOIN_CODE_ROTATE',
    ownerSource: 'H',
    owner: 'GroupStateInboxHandler.processGroupStateMutation',
    typeOwnerSource: 'I',
    dispatchSource: 'G',
    operationDiscriminant: 'rotate-group-join-code',
    familyRegistrationMarker: 'registerGroupAdmissionRoutes',
    rootSource: 'gr',
    constructionRootMarker: 'registerGroupStateRoutes',
    familyOwnerOrder: 2,
  },
  {
    transport: 'HTTP',
    entrypoint: `POST ${GROUP_ITEM_ROUTE}/admissions/:principalId/grant`,
    type: 'GROUP_ADMISSION_GRANT',
    source: 'ga',
    registrationMarker: 'registerGrantGroupAdmissionRoute',
    enqueueSource: 'gc',
    enqueueMarker: 'AppInboxType.GROUP_ADMISSION_GRANT',
    ownerSource: 'H',
    owner: 'GroupStateInboxHandler.processGroupStateMutation',
    typeOwnerSource: 'I',
    dispatchSource: 'G',
    operationDiscriminant: 'grant-group-admission',
    familyRegistrationMarker: 'registerGroupAdmissionRoutes',
    rootSource: 'gr',
    constructionRootMarker: 'registerGroupStateRoutes',
    familyOwnerOrder: 5,
  },
  {
    transport: 'HTTP',
    entrypoint: `POST ${GROUP_ITEM_ROUTE}/admissions/:principalId/decline`,
    type: 'GROUP_ADMISSION_DECLINE',
    source: 'ga',
    registrationMarker: 'registerDeclineGroupAdmissionRoute',
    enqueueSource: 'gc',
    enqueueMarker: 'AppInboxType.GROUP_ADMISSION_DECLINE',
    ownerSource: 'H',
    owner: 'GroupStateInboxHandler.processGroupStateMutation',
    typeOwnerSource: 'I',
    dispatchSource: 'G',
    operationDiscriminant: 'decline-group-admission',
    familyRegistrationMarker: 'registerGroupAdmissionRoutes',
    rootSource: 'gr',
    constructionRootMarker: 'registerGroupStateRoutes',
    familyOwnerOrder: 6,
  },
  {
    transport: 'HTTP',
    entrypoint: `POST ${GROUP_ITEM_ROUTE}/members/:principalId/remove`,
    type: 'GROUP_MEMBER_REMOVE',
    source: 'gm',
    registrationMarker: 'registerRemoveGroupMemberRoute',
    enqueueSource: 'gc',
    enqueueMarker: 'AppInboxType.GROUP_MEMBER_REMOVE',
    ownerSource: 'H',
    owner: 'GroupStateInboxHandler.processGroupStateMutation',
    typeOwnerSource: 'I',
    dispatchSource: 'G',
    operationDiscriminant: 'remove-group-member',
    familyRegistrationMarker: 'registerGroupMembershipRoutes',
    rootSource: 'gr',
    constructionRootMarker: 'registerGroupStateRoutes',
    familyOwnerOrder: 0,
  },
  {
    transport: 'HTTP',
    entrypoint: `POST ${GROUP_ITEM_ROUTE}/members/:principalId/ban`,
    type: 'GROUP_MEMBER_BAN',
    source: 'gm',
    registrationMarker: 'registerBanGroupMemberRoute',
    enqueueSource: 'gc',
    enqueueMarker: 'AppInboxType.GROUP_MEMBER_BAN',
    ownerSource: 'H',
    owner: 'GroupStateInboxHandler.processGroupStateMutation',
    typeOwnerSource: 'I',
    dispatchSource: 'G',
    operationDiscriminant: 'ban-group-member',
    familyRegistrationMarker: 'registerGroupMembershipRoutes',
    rootSource: 'gr',
    constructionRootMarker: 'registerGroupStateRoutes',
    familyOwnerOrder: 1,
  },
  {
    transport: 'HTTP',
    entrypoint: `POST ${GROUP_ITEM_ROUTE}/members/:principalId/unban`,
    type: 'GROUP_MEMBER_UNBAN',
    source: 'gm',
    registrationMarker: 'registerUnbanGroupMemberRoute',
    enqueueSource: 'gc',
    enqueueMarker: 'AppInboxType.GROUP_MEMBER_UNBAN',
    ownerSource: 'H',
    owner: 'GroupStateInboxHandler.processGroupStateMutation',
    typeOwnerSource: 'I',
    dispatchSource: 'G',
    operationDiscriminant: 'unban-group-member',
    familyRegistrationMarker: 'registerGroupMembershipRoutes',
    rootSource: 'gr',
    constructionRootMarker: 'registerGroupStateRoutes',
    familyOwnerOrder: 2,
  },
  {
    transport: 'HTTP',
    entrypoint: `PUT ${GROUP_ITEM_ROUTE}/members/:principalId/role`,
    type: 'GROUP_MEMBER_ROLE_SET',
    source: 'gm',
    registrationMarker: 'registerSetGroupMemberRoleRoute',
    enqueueSource: 'gc',
    enqueueMarker: 'AppInboxType.GROUP_MEMBER_ROLE_SET',
    ownerSource: 'H',
    owner: 'GroupStateInboxHandler.processGroupStateMutation',
    typeOwnerSource: 'I',
    dispatchSource: 'G',
    operationDiscriminant: 'set-group-member-role',
    familyRegistrationMarker: 'registerGroupMembershipRoutes',
    rootSource: 'gr',
    constructionRootMarker: 'registerGroupStateRoutes',
    familyOwnerOrder: 3,
  },
  {
    transport: 'HTTP',
    entrypoint: `POST ${GROUP_ITEM_ROUTE}/owner/transfer`,
    type: 'GROUP_OWNERSHIP_TRANSFER',
    source: 'gm',
    registrationMarker: 'registerTransferGroupOwnershipRoute',
    enqueueSource: 'gc',
    enqueueMarker: 'AppInboxType.GROUP_OWNERSHIP_TRANSFER',
    ownerSource: 'H',
    owner: 'GroupStateInboxHandler.processGroupStateMutation',
    typeOwnerSource: 'I',
    dispatchSource: 'G',
    operationDiscriminant: 'transfer-group-ownership',
    familyRegistrationMarker: 'registerGroupMembershipRoutes',
    rootSource: 'gr',
    constructionRootMarker: 'registerGroupStateRoutes',
    familyOwnerOrder: 4,
  },
  {
    transport: 'HTTP',
    entrypoint: `PUT ${GROUP_ITEM_ROUTE}/members/:principalId`,
    type: 'GROUP_MEMBER_UPSERT',
    source: 'gm',
    registrationMarker: 'registerUpsertSelfGroupMemberRoute',
    enqueueSource: 'gc',
    enqueueMarker: 'AppInboxType.GROUP_MEMBER_UPSERT',
    ownerSource: 'H',
    owner: 'GroupStateInboxHandler.processGroupStateMutation',
    typeOwnerSource: 'I',
    dispatchSource: 'G',
    operationDiscriminant: 'upsert-group-member',
    familyRegistrationMarker: 'registerGroupMembershipRoutes',
    rootSource: 'gr',
    constructionRootMarker: 'registerGroupStateRoutes',
    familyOwnerOrder: 5,
  },
  {
    transport: 'HTTP',
    entrypoint: `PUT ${GROUP_ITEM_ROUTE}/sessions/:sessionId`,
    type: 'GROUP_PRESENCE_CONNECT',
    source: 'gp',
    registrationMarker: 'registerConnectGroupPresenceRoute',
    enqueueSource: 'gc',
    enqueueMarker: 'AppInboxType.GROUP_PRESENCE_CONNECT',
    ownerSource: 'H',
    owner: 'GroupStateInboxHandler.processGroupStateMutation',
    typeOwnerSource: 'I',
    dispatchSource: 'G',
    operationDiscriminant: 'connect-group-presence',
    familyRegistrationMarker: 'registerGroupPresenceRoutes',
    rootSource: 'gr',
    constructionRootMarker: 'registerGroupStateRoutes',
    familyOwnerOrder: 0,
  },
  {
    transport: 'HTTP',
    entrypoint: `POST ${GROUP_ITEM_ROUTE}/sessions/:sessionId/heartbeat`,
    type: 'GROUP_PRESENCE_HEARTBEAT',
    source: 'gp',
    registrationMarker: 'registerHeartbeatGroupPresenceRoute',
    enqueueSource: 'gc',
    enqueueMarker: 'AppInboxType.GROUP_PRESENCE_HEARTBEAT',
    ownerSource: 'H',
    owner: 'GroupStateInboxHandler.processGroupStateMutation',
    typeOwnerSource: 'I',
    dispatchSource: 'G',
    operationDiscriminant: 'heartbeat-group-presence',
    familyRegistrationMarker: 'registerGroupPresenceRoutes',
    rootSource: 'gr',
    constructionRootMarker: 'registerGroupStateRoutes',
    familyOwnerOrder: 1,
  },
  {
    transport: 'HTTP',
    entrypoint: `POST ${GROUP_ITEM_ROUTE}/sessions/:sessionId/disconnect`,
    type: 'GROUP_PRESENCE_DISCONNECT',
    source: 'gp',
    registrationMarker: 'registerDisconnectGroupPresenceRoute',
    enqueueSource: 'gc',
    enqueueMarker: 'AppInboxType.GROUP_PRESENCE_DISCONNECT',
    ownerSource: 'H',
    owner: 'GroupStateInboxHandler.processGroupStateMutation',
    typeOwnerSource: 'I',
    dispatchSource: 'G',
    operationDiscriminant: 'disconnect-group-presence',
    familyRegistrationMarker: 'registerGroupPresenceRoutes',
    rootSource: 'gr',
    constructionRootMarker: 'registerGroupStateRoutes',
    familyOwnerOrder: 2,
  },
  {
    transport: 'MAINTENANCE',
    entrypoint: 'group presence expiry reconciliation',
    type: 'GROUP_PRESENCE_EXPIRE',
    source: 'e',
    registrationMarker: 'enqueuePresenceExpiryReconciliation',
    enqueueSource: 'e',
    enqueueMarker: 'enqueueExpiredPresenceSessions',
    ownerSource: 'H',
    owner: 'GroupStateInboxHandler.processGroupStateMutation',
    typeOwnerSource: 'I',
    dispatchSource: 'G',
  },
  {
    transport: 'MAINTENANCE',
    entrypoint: 'formation criterion evaluation',
    type: 'GROUP_FORMATION_CRITERION',
    source: 'ci',
    registrationMarker: 'submitFormationCriterionCommand',
    enqueueSource: 'ci',
    enqueueMarker: 'enqueueFormationCriterionCommand',
    ownerSource: 'H',
    owner: 'GroupStateInboxHandler.processGroupStateMutation',
    typeOwnerSource: 'I',
    dispatchSource: 'G',
  },
  {
    transport: 'WS_LIFECYCLE',
    entrypoint: 'websocket onClose group cleanup',
    type: 'GROUP_PRESENCE_SESSION_CLEANUP',
    source: 'l',
    registrationMarker: 'onClose:',
    enqueueSource: 'l',
    enqueueMarker: 'enqueueGroupSessionCleanup',
    ownerSource: 'P',
    owner: 'processGroupSessionCleanup',
    typeOwnerSource: 'G',
    dispatchSource: 'G',
  },
  {
    transport: 'HTTP',
    entrypoint: `PUT ${TOPOLOGY_ROUTE}/config`,
    type: 'TOPOLOGY_CONFIG_PUT',
    source: 't',
    registrationMarker: '/topology/config',
    enqueueSource: 't',
    enqueueMarker: 'AppInboxType.TOPOLOGY_CONFIG_PUT',
    ownerSource: 'T',
    owner: 'TopologyAppInboxHandler.processMutation',
    typeOwnerSource: 'G',
    dispatchSource: 'G',
  },
  {
    transport: 'HTTP',
    entrypoint: `DELETE ${TOPOLOGY_ROUTE}/config`,
    type: 'TOPOLOGY_CONFIG_DELETE',
    source: 't',
    registrationMarker: '/topology/config',
    enqueueSource: 't',
    enqueueMarker: 'AppInboxType.TOPOLOGY_CONFIG_DELETE',
    ownerSource: 'T',
    owner: 'TopologyAppInboxHandler.processMutation',
    typeOwnerSource: 'G',
    dispatchSource: 'G',
  },
  {
    transport: 'HTTP',
    entrypoint: `PUT ${TOPOLOGY_ROUTE}/override`,
    type: 'TOPOLOGY_OVERRIDE_PUT',
    source: 't',
    registrationMarker: '/topology/override',
    enqueueSource: 't',
    enqueueMarker: 'AppInboxType.TOPOLOGY_OVERRIDE_PUT',
    ownerSource: 'T',
    owner: 'TopologyAppInboxHandler.processMutation',
    typeOwnerSource: 'G',
    dispatchSource: 'G',
  },
  {
    transport: 'HTTP',
    entrypoint: `DELETE ${TOPOLOGY_ROUTE}/override`,
    type: 'TOPOLOGY_OVERRIDE_DELETE',
    source: 't',
    registrationMarker: '/topology/override',
    enqueueSource: 't',
    enqueueMarker: 'AppInboxType.TOPOLOGY_OVERRIDE_DELETE',
    ownerSource: 'T',
    owner: 'TopologyAppInboxHandler.processMutation',
    typeOwnerSource: 'G',
    dispatchSource: 'G',
  },
  {
    transport: 'HTTP',
    entrypoint: `POST ${TOPOLOGY_ROUTE}/reconfigure`,
    type: 'TOPOLOGY_RECONFIGURE',
    source: 't',
    registrationMarker: '/topology/reconfigure',
    enqueueSource: 't',
    enqueueMarker: 'AppInboxType.TOPOLOGY_RECONFIGURE',
    ownerSource: 'T',
    owner: 'TopologyAppInboxHandler.processMutation',
    typeOwnerSource: 'G',
    dispatchSource: 'G',
  },
  {
    transport: 'HTTP',
    entrypoint: 'POST /api/admin/operations/topology/recompute',
    type: 'TOPOLOGY_RECONFIGURE',
    source: 'ad',
    registrationMarker: "'/api/admin/operations/topology/recompute'",
    enqueueSource: 'ag',
    enqueueMarker: 'processAuthenticatedEntryUntilCompletionResult',
    ownerSource: 'T',
    owner: 'TopologyAppInboxHandler.processMutation',
    typeOwnerSource: 'G',
    dispatchSource: 'G',
  },
  {
    transport: 'WS_INBOX',
    entrypoint: 'topic rallar/rtt',
    type: 'RTC_RTT_SUBMIT',
    source: 's',
    registrationMarker: 'AppTopics.rtt',
    enqueueSource: 's',
    enqueueMarker: 'enqueueRtcRttMutation',
    ownerSource: 'R',
    owner: 'RtcRttAppInboxHandler.processMutation',
    typeOwnerSource: 'G',
    dispatchSource: 'G',
  },
  {
    transport: 'WS_INBOX',
    entrypoint: 'topic rallar/crdt/update',
    type: 'CRDT_UPDATE_APPEND',
    source: 'd',
    registrationMarker: "accepted.kind === 'update'",
    enqueueSource: 'd',
    enqueueMarker: 'mutationIngress.enqueueUpdate',
    ownerSource: 'D',
    owner: 'AppCrdtInboxService.processCommand',
  },
  {
    transport: 'HTTP',
    entrypoint: 'POST /api/crdt/admin/documents/rebuild-projection',
    type: 'CRDT_PROJECTION_REBUILD',
    source: 'cr',
    registrationMarker: "'/api/crdt/admin/documents/rebuild-projection'",
    enqueueSource: 'cm',
    enqueueMarker: 'writeCrdtCommandUntilCompletion',
    ownerSource: 'D',
    owner: 'AppCrdtInboxService.processCommand',
    typeOwnerSource: 'D',
    dispatchSource: 'D',
    operationDiscriminant: 'rebuild-projection',
  },
  {
    transport: 'HTTP',
    entrypoint: 'POST /api/crdt/admin/documents/compact',
    type: 'CRDT_SNAPSHOT_COMPACT',
    source: 'cr',
    registrationMarker: "'/api/crdt/admin/documents/compact'",
    enqueueSource: 'cm',
    enqueueMarker: 'writeCrdtCommandUntilCompletion',
    ownerSource: 'D',
    owner: 'AppCrdtInboxService.processCommand',
    typeOwnerSource: 'D',
    dispatchSource: 'D',
    operationDiscriminant: 'compact',
  },
  {
    transport: 'HTTP',
    entrypoint: 'POST /api/admin/operations/crdt/compact',
    type: 'CRDT_SNAPSHOT_COMPACT',
    source: 'ad',
    registrationMarker: "'/api/admin/operations/crdt/compact'",
    enqueueSource: 'ag',
    enqueueMarker: 'writeCrdtAdminMutation',
    ownerSource: 'D',
    owner: 'AppCrdtInboxService.processCommand',
    typeOwnerSource: 'D',
    dispatchSource: 'D',
    operationDiscriminant: 'compact',
  },
  {
    transport: 'HTTP',
    entrypoint: 'POST /api/crdt/admin/documents/lifecycle',
    type: 'CRDT_LIFECYCLE_UPDATE',
    source: 'cr',
    registrationMarker: "'/api/crdt/admin/documents/lifecycle'",
    enqueueSource: 'cm',
    enqueueMarker: 'writeCrdtCommandUntilCompletion',
    ownerSource: 'D',
    owner: 'AppCrdtInboxService.processCommand',
    typeOwnerSource: 'D',
    dispatchSource: 'D',
    operationDiscriminant: 'lifecycle',
  },
  {
    transport: 'HTTP',
    entrypoint: 'POST /api/admin/operations/crdt/lifecycle',
    type: 'CRDT_LIFECYCLE_UPDATE',
    source: 'ad',
    registrationMarker: "'/api/admin/operations/crdt/lifecycle'",
    enqueueSource: 'ag',
    enqueueMarker: 'writeCrdtAdminMutation',
    ownerSource: 'D',
    owner: 'AppCrdtInboxService.processCommand',
    typeOwnerSource: 'D',
    dispatchSource: 'D',
    operationDiscriminant: 'lifecycle',
  },
  {
    transport: 'HTTP',
    entrypoint: 'POST /api/crdt/admin/documents/erase',
    type: 'CRDT_ERASE',
    source: 'cr',
    registrationMarker: "'/api/crdt/admin/documents/erase'",
    enqueueSource: 'cm',
    enqueueMarker: 'writeCrdtCommandUntilCompletion',
    ownerSource: 'D',
    owner: 'AppCrdtInboxService.processCommand',
    typeOwnerSource: 'D',
    dispatchSource: 'D',
    operationDiscriminant: 'erase',
  },
  {
    transport: 'HTTP',
    entrypoint: 'POST /api/admin/operations/crdt/erase',
    type: 'CRDT_ERASE',
    source: 'ad',
    registrationMarker: "'/api/admin/operations/crdt/erase'",
    enqueueSource: 'ag',
    enqueueMarker: 'writeCrdtAdminMutation',
    ownerSource: 'D',
    owner: 'AppCrdtInboxService.processCommand',
    typeOwnerSource: 'D',
    dispatchSource: 'D',
    operationDiscriminant: 'erase',
  },
  {
    transport: 'HTTP',
    entrypoint: 'POST /api/admin/operations/maintenance/prune-expired',
    type: 'ADMIN_PRUNE_EXPIRED',
    source: 'ad',
    registrationMarker: "'/api/admin/operations/maintenance/prune-expired'",
    enqueueSource: 'ag',
    enqueueMarker: 'appAdmin.pruneExpired',
    ownerSource: 'N',
    owner: 'AppAdminInboxService.processCommand',
  },
];
