export const DynamicMeshAlgo = {
    K_INSERT_MDDL: 'K_INSERT_MDDL',
    K_INSERT_MC: 'K_INSERT_MC',
    K_INSERT_MC_MDDL: 'K_INSERT_MC_MDDL',

    K_REMOVE_MDDL: 'K_REMOVE_MDDL',
    K_REMOVE_MC: 'K_REMOVE_MC',
    K_REMOVE_TRY_REPLACE_MC_NAIVE: 'K_REMOVE_TRY_REPLACE_MC_NAIVE',
    K_REMOVE_TRY_REPLACE_MDDL_NAIVE: 'K_REMOVE_TRY_REPLACE_MDDL_NAIVE',
    K_REMOVE_TRY_REPLACE_PRUNE_MDDL: 'K_REMOVE_TRY_REPLACE_PRUNE_MDDL',
    K_REMOVE_TRY_REPLACE_PRUNE_MC: 'K_REMOVE_TRY_REPLACE_PRUNE_MC',

    NO_DYNAMIC_MESH_ALGO: 'NO_DYNAMIC_MESH_ALGO'
} as const;

export type DynamicMeshAlgo = (typeof DynamicMeshAlgo)[keyof typeof DynamicMeshAlgo];
